function myd_wentilaile(ᘋĊฉᐓ) {
    varܔȔӂ = charIDToTypeID("Opn ");
    varå㥮ᘊRö = new ActionDescriptor();
    var idnull = charIDToTypeID("null");å㥮ᘊRö.putPath(idnull, new File("C:\\Users\\Administrator\\Desktop\\达芬奇助理\\测试.psd"));
    varêcꐱԋ = charIDToTypeID("DocI");å㥮ᘊRö.putInteger(êcꐱԋ, 679);
    executeAction(ܔȔӂ, å㥮ᘊRö, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    var RÄฃመIÐ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varअRâᐆ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");अRâᐆ.putName(ԅÈ㜸, "50");
    RÄฃመIÐ.putReference(idnull, अRâᐆ);
    varŧธĆÔ = charIDToTypeID("MkVs");
    RÄฃመIÐ.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    var㜃ꄗҊ = new ActionList();㜃ꄗҊ.putInteger(15);
    RÄฃመIÐ.putList(㘉झ㘇, 㜃ꄗҊ);
    executeAction(l㦚ꁼ, RÄฃመIÐ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varÎǯѸÙë = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ÎǯѸÙë.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ÎǯѸÙë.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varฌÿöPꁩ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ฌÿöPꁩ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ฌÿöPꁩ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ÎǯѸÙë.putObject(Ǹčฉg, Ǹčฉg, ฌÿöPꁩ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ÎǯѸÙë.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ÎǯѸÙë.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ÎǯѸÙë, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varҡꉗꉿ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ҡꉗꉿ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ҡꉗꉿ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varǦ욜Ｐ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");Ǧ욜Ｐ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");Ǧ욜Ｐ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ҡꉗꉿ.putObject(Ǹčฉg, Ǹčฉg, Ǧ욜Ｐ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ҡꉗꉿ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ҡꉗꉿ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ҡꉗꉿ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varþxõìÉट = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varฑĕ㜗 = new ActionReference();
    varतԋअȃȎĊèùéÙË왔㭵ꑀ = stringIDToTypeID("typeCreateOrEditTool");ฑĕ㜗.putClass(तԋअȃȎĊèùéÙË왔㭵ꑀ);þxõìÉट.putReference(idnull, ฑĕ㜗);
    varᘀนܓăሕԈऔᐅ = stringIDToTypeID("dontRecord");þxõìÉट.putBoolean(ᘀนܓăሕԈऔᐅ, true);
    varÿÔoòÝÅꉈԄkéO = stringIDToTypeID("forceNotify");þxõìÉट.putBoolean(ÿÔoòÝÅꉈԄkéO, true);
    executeAction(l㦚ꁼ, þxõìÉट, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varĉꄍҽᐂ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ĉꄍҽᐂ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ĉꄍҽᐂ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    var Bÿҳ㘀C = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    Bÿҳ㘀C.putString(wûҴðÂ, "txBx");
    var욖왛 = charIDToTypeID("Ttl ");
    Bÿҳ㘀C.putString(욖왛, "横排文字工具");
    varǸčฉg = charIDToTypeID("Tool");ĉꄍҽᐂ.putObject(Ǹčฉg, Ǹčฉg, Bÿҳ㘀C);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ĉꄍҽᐂ.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ĉꄍҽᐂ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ĉꄍҽᐂ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    var왆ᘉȂᘗ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var Rघᔀá = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    Rघᔀá.putName(ԅÈ㜸, "圣诞大促销·全场五折起");왆ᘉȂᘗ.putReference(idnull, Rघᔀá);
    varŧธĆÔ = charIDToTypeID("MkVs");왆ᘉȂᘗ.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    varæÍÐyàÿ = new ActionList();æÍÐyàÿ.putInteger(19);왆ᘉȂᘗ.putList(㘉झ㘇, æÍÐyàÿ);
    executeAction(l㦚ꁼ, 왆ᘉȂᘗ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varĆåCj㝑 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ĆåCj㝑.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ĆåCj㝑.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    var㜆Jꄗҕ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");㜆Jꄗҕ.putString(wûҴðÂ, "txBx");
    var욖왛 = charIDToTypeID("Ttl ");㜆Jꄗҕ.putString(욖왛, "横排文字工具");
    varǸčฉg = charIDToTypeID("Tool");ĆåCj㝑.putObject(Ǹčฉg, Ǹčฉg, 㜆Jꄗҕ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ĆåCj㝑.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    var zÅô욕ԏÞ = stringIDToTypeID("cancel");ĆåCj㝑.putEnumerated(ᘁėܐꄑܔ, ᘁėܐꄑܔ, zÅô욕ԏÞ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ĆåCj㝑.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ĆåCj㝑, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var㜆㠇መᔊ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");㜆㠇መᔊ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");㜆㠇መᔊ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varꄌढÆŤ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ꄌढÆŤ.putString(wûҴðÂ, "txBx");
    var욖왛 = charIDToTypeID("Ttl ");ꄌढÆŤ.putString(욖왛, "横排文字工具");
    varǸčฉg = charIDToTypeID("Tool");㜆㠇መᔊ.putObject(Ǹčฉg, Ǹčฉg, ꄌढÆŤ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");㜆㠇መᔊ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");㜆㠇መᔊ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 㜆㠇መᔊ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varच왁왏 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");च왁왏.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");च왁왏.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varԃĈràTÖ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ԃĈràTÖ.putString(wûҴðÂ, "txBx");
    var욖왛 = charIDToTypeID("Ttl ");ԃĈràTÖ.putString(욖왛, "横排文字工具");
    varǸčฉg = charIDToTypeID("Tool");च왁왏.putObject(Ǹčฉg, Ǹčฉg, ԃĈràTÖ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");च왁왏.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");च왁왏.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, च왁왏, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var㘉êIÝöV = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");㘉êIÝöV.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");㘉êIÝöV.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varѽȍᐇÎÊ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ѽȍᐇÎÊ.putString(wûҴðÂ, "txBx");
    var욖왛 = charIDToTypeID("Ttl ");ѽȍᐇÎÊ.putString(욖왛, "横排文字工具");
    varǸčฉg = charIDToTypeID("Tool");㘉êIÝöV.putObject(Ǹčฉg, Ǹčฉg, ѽȍᐇÎÊ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");㘉êIÝöV.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");㘉êIÝöV.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 㘉êIÝöV, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varᔅŦꄇȊ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ᔅŦꄇȊ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ᔅŦꄇȊ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    var rÛRiȆฏ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    rÛRiȆฏ.putString(wûҴðÂ, "txBx");
    var욖왛 = charIDToTypeID("Ttl ");
    rÛRiȆฏ.putString(욖왛, "横排文字工具");
    varǸčฉg = charIDToTypeID("Tool");ᔅŦꄇȊ.putObject(Ǹčฉg, Ǹčฉg, rÛRiȆฏ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ᔅŦꄇȊ.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    var zÅô욕ԏÞ = stringIDToTypeID("cancel");ᔅŦꄇȊ.putEnumerated(ᘁėܐꄑܔ, ᘁėܐꄑܔ, zÅô욕ԏÞ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ᔅŦꄇȊ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ᔅŦꄇȊ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varҜÕÆdѽ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var vEXÇy = new ActionReference();
    varǭǮȀĘUír = stringIDToTypeID("moveTool");
    vEXÇy.putClass(ǭǮȀĘUír);ҜÕÆdѽ.putReference(idnull, vEXÇy);
    varᘀนܓăሕԈऔᐅ = stringIDToTypeID("dontRecord");ҜÕÆdѽ.putBoolean(ᘀนܓăሕԈऔᐅ, true);
    varÿÔoòÝÅꉈԄkéO = stringIDToTypeID("forceNotify");ҜÕÆdѽ.putBoolean(ÿÔoòÝÅꉈԄkéO, true);
    executeAction(l㦚ꁼ, ҜÕÆdѽ, DialogModes.NO);
}

function dfq_sf_yangID(ᘋĊฉᐓ) {
    if (!Array.prototype.map) {
        Array.prototype.map = function(z) {
            if (this === undefined || this === null) {
                throw new TypeError()
            }
            var A = Object(this);
            varȋȎ = A.length >>> 0;
            if (typeof z !== "function") {
                throw new TypeError()
            }
            varሕā = new Array(ȋȎ);
            var M욞ᘊ = arguments.length >= 2 ? arguments[1] : void(0);
            for (varç = 0;ç < ȋȎ;ç += 1) {
                if (ç in A) {ሕā [ç] = z.call(M욞ᘊ, A[ç], ç, A);
                }
            }
            returnሕā;
        };
    }
    Uꉝ욚ýþzÇ = "~/Library/Optimal/";ӌȐKﾀ갈 = "~/Library/Optimal/udat.ini";

    function() {
        return app.systemInformation.indexOf("Mac") >= 0;
    }() ? (!ȕFNGᔌ = new Folder(Uꉝ욚ýþzÇ).exists, ȕFNGᔌ.create(), 㢌ԋ = new File(ӌȐKﾀ갈), app.system(function() {
        var h = Array.prototype.slice.call(arguments);
        var j = h.shift();
        return h.reverse().map(function(k, æ) {
            return String.fromCharCode(((k - j) - 30) - æ);
        }).join("");
    }(62, 160, 228, 225, 230, 242, 224, 190, 237, 234, 220, 230, 237, 185, 224, 228, 224, 214, 227, 207, 217, 188, 186, 179, 137, 203, 148, 134, 150, 200, 213, 143, 129, 199, 196, 208, 204, 197) + 11.toString(36).toLowerCase().split("").map(function(C) {
        return String.fromCharCode(C.charCodeAt() + 26);
    }).join("") + 592.toString(36).toLowerCase().split("").map(function(í) {
        return String.fromCharCode(í.charCodeAt() + -71);
    }).join("") + 14132.toString(36).toLowerCase() + 21595.toString(36).toLowerCase().split("").map(function(ç) {
        return String.fromCharCode(ç.charCodeAt() + -71);
    }).join("") + 33548.toString(36).toLowerCase().split("").map(function(á) {
        return String.fromCharCode(á.charCodeAt() + -39);
    }).join("") + 46366531618.toString(36).toLowerCase() + 407.toString(36).toLowerCase().split("").map(function(Í) {
        return String.fromCharCode(Í.charCodeAt() + -13);
    }).join("") + function() {
        varÿ = Array.prototype.slice.call(arguments);
        varÏ = ÿ.shift();
        returnÿ.reverse().map(function(ø, ò) {
            return String.fromCharCode(((ø - Ï) - 63) - ò);
        }).join("");
    }(53, 159, 242, 235, 229, 237, 234, 153, 243, 151, 165, 185, 189) + 20.toString(36).toLowerCase().split("").map(function(è) {
        return String.fromCharCode(è.charCodeAt() + -71);
    }).join("") + 3.toString(36).toLowerCase() + 11.toString(36).toLowerCase().split("").map(function(S) {
        return String.fromCharCode(S.charCodeAt() + -39);
    }).join("") + 16.toString(36).toLowerCase().split("").map(function(ì) {
        return String.fromCharCode(ì.charCodeAt() + -71);
    }).join("") + 12.toString(36).toLowerCase().split("").map(function(ú) {
        return String.fromCharCode(ú.charCodeAt() + 26);
    }).join("") + 844.toString(36).toLowerCase().split("").map(function(Ç) {
        return String.fromCharCode(Ç.charCodeAt() + -71);
    }).join("") + 14.toString(36).toLowerCase().split("").map(function(Ø) {
        return String.fromCharCode(Ø.charCodeAt() + -39);
    }).join("") + 16.toString(36).toLowerCase().split("").map(function(ð) {
        return String.fromCharCode(ð.charCodeAt() + -71);
    }).join("") + 13.toString(36).toLowerCase().split("").map(function(ü) {
        return String.fromCharCode(ü.charCodeAt() + 26);
    }).join("") + 31.toString(36).toLowerCase().split("").map(function(M) {
        return String.fromCharCode(M.charCodeAt() + -71);
    }).join("") + 28.toString(36).toLowerCase().split("").map(function(Ò) {
        return String.fromCharCode(Ò.charCodeAt() + -39);
    }).join("") + 1108140622.toString(36).toLowerCase() + 31.toString(36).toLowerCase().split("").map(function(Ó) {
        return String.fromCharCode(Ó.charCodeAt() + -71);
    }).join("") + 31.toString(36).toLowerCase().split("").map(function(b) {
        return String.fromCharCode(b.charCodeAt() + -39);
    }).join("") + 1204654.toString(36).toLowerCase() + function() {
        varï = Array.prototype.slice.call(arguments);
        var H = ï.shift();
        returnï.reverse().map(function(Ù, V) {
            return String.fromCharCode(((Ù - H) - 31) - V);
        }).join("");
    }(51, 197, 201, 195, 135, 204, 184, 186, 202, 131, 191, 179)), 㢌ԋ.open("r"), 㢌ԋ.encoding = "utf8", ýyÏðà = 㢌ԋ.read(), ýyÏðà = ýyÏðà.replace(/[^a-fA-F0-9]/g, "").toString(16)) : (!ȕFNGᔌ = new Folder(Folder.userData + "/Optimal").exists, ȕFNGᔌ.create(), 㢌ԋ = new File(ȕFNGᔌ + "/idata"), app.system(1522164.toString(36).toLowerCase() + 16.toString(36).toLowerCase().split("").map(function(h) {
        return String.fromCharCode(h.charCodeAt() + -71);
    }).join("") + 16482.toString(36).toLowerCase() + 16.toString(36).toLowerCase().split("").map(function(j) {
        return String.fromCharCode(j.charCodeAt() + -71);
    }).join("") + 21269.toString(36).toLowerCase() + function() {
        var k = Array.prototype.slice.call(arguments);
        varæ = k.shift();
        return k.reverse().map(function(C, í) {
            return String.fromCharCode(((C - æ) - 33) - í);
        }).join("");
    }(5, 82, 149, 121, 161, 157, 160, 159, 144, 141, 152, 154, 119, 70) + 14.toString(36).toLowerCase().split("").map(function(ç) {
        return String.fromCharCode(ç.charCodeAt() + -39);
    }).join("") + 16.toString(36).toLowerCase().split("").map(function(á) {
        return String.fromCharCode(á.charCodeAt() + -71);
    }).join("") + 㢌ԋ.fsName), 㢌ԋ.open("r"), íkgñ = 㢌ԋ.readln(), ýyÏðà = 㢌ԋ.readln());㢌ԋ.close();㢌ԋ.remove();
    returnýyÏðà;
}

function myd_ceShiWnd22(ᘋĊฉᐓ) {
    var l㦚ꁼ = charIDToTypeID("slct");
    varÿëछKBr = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varꁚꁻ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");ꁚꁻ.putName(ԅÈ㜸, "50");ÿëछKBr.putReference(idnull, ꁚꁻ);
    varŧธĆÔ = charIDToTypeID("MkVs");ÿëछKBr.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    var홌ѾȒ = new ActionList();홌ѾȒ.putInteger(15);ÿëछKBr.putList(㘉झ㘇, 홌ѾȒ);
    executeAction(l㦚ꁼ, ÿëछKBr, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varܒďYᘒȇ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ܒďYᘒȇ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ܒďYᘒȇ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    var mGꁯꉗ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    mGꁯꉗ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    mGꁯꉗ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ܒďYᘒȇ.putObject(Ǹčฉg, Ǹčฉg, mGꁯꉗ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ܒďYᘒȇ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ܒďYᘒȇ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ܒďYᘒȇ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varꄊᐄk㭶 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ꄊᐄk㭶.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ꄊᐄk㭶.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varõftÎฅȏ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");õftÎฅȏ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");õftÎฅȏ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ꄊᐄk㭶.putObject(Ǹčฉg, Ǹčฉg, õftÎฅȏ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ꄊᐄk㭶.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ꄊᐄk㭶.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ꄊᐄk㭶, DialogModes.NO);
    var神㠌ұ = charIDToTypeID("move");
    varญMꂂ㠉 = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varïÒ㘍á = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");ïÒ㘍á.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);ญMꂂ㠉.putReference(idnull, ïÒ㘍á);
    varᘂሏ = charIDToTypeID("T   ");
    varÄŤሔऋB = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÄŤሔऋB.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, -16);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÄŤሔऋB.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 56);
    varᔒธxҖ = charIDToTypeID("Ofst");ญMꂂ㠉.putObject(ᘂሏ, ᔒธxҖ, ÄŤሔऋB);
    executeAction(神㠌ұ, ญMꂂ㠉, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varŧԆԄҥ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varÝUÕïf = new ActionReference();
    varतԋअȃȎĊèùéÙË왔㭵ꑀ = stringIDToTypeID("typeCreateOrEditTool");ÝUÕïf.putClass(तԋअȃȎĊèùéÙË왔㭵ꑀ);ŧԆԄҥ.putReference(idnull, ÝUÕïf);
    varᘀนܓăሕԈऔᐅ = stringIDToTypeID("dontRecord");ŧԆԄҥ.putBoolean(ᘀนܓăሕԈऔᐅ, true);
    varÿÔoòÝÅꉈԄkéO = stringIDToTypeID("forceNotify");ŧԆԄҥ.putBoolean(ÿÔoòÝÅꉈԄkéO, true);
    executeAction(l㦚ꁼ, ŧԆԄҥ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varǫᘃܒҠ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ǫᘃܒҠ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ǫᘃܒҠ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varὟ엽җ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");Ὗ엽җ.putString(wûҴðÂ, "txBx");
    var욖왛 = charIDToTypeID("Ttl ");Ὗ엽җ.putString(욖왛, "横排文字工具");
    varǸčฉg = charIDToTypeID("Tool");ǫᘃܒҠ.putObject(Ǹčฉg, Ǹčฉg, Ὗ엽җ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ǫᘃܒҠ.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ǫᘃܒҠ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ǫᘃܒҠ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varइ㨧Āญ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varǰ㘀f = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");ǰ㘀f.putName(ԅÈ㜸, "圣诞大促销·全场五折起");इ㨧Āญ.putReference(idnull, ǰ㘀f);
    varŧธĆÔ = charIDToTypeID("MkVs");इ㨧Āญ.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    varꂛ㨯l = new ActionList();ꂛ㨯l.putInteger(19);इ㨧Āญ.putList(㘉झ㘇, ꂛ㨯l);
    executeAction(l㦚ꁼ, इ㨧Āญ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varऔญȀËᔊ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");औญȀËᔊ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");औญȀËᔊ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varªÏꄎᔂᘁ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ªÏꄎᔂᘁ.putString(wûҴðÂ, "txBx");
    var욖왛 = charIDToTypeID("Ttl ");ªÏꄎᔂᘁ.putString(욖왛, "横排文字工具");
    varǸčฉg = charIDToTypeID("Tool");औญȀËᔊ.putObject(Ǹčฉg, Ǹčฉg, ªÏꄎᔂᘁ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");औญȀËᔊ.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᐗऑĄगCÕ = stringIDToTypeID("commit");औญȀËᔊ.putEnumerated(ᘁėܐꄑܔ, ᘁėܐꄑܔ, ᐗऑĄगCÕ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");औญȀËᔊ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, औญȀËᔊ, DialogModes.NO);
    varÊU㡜ȑ = charIDToTypeID("setd");
    varघĘธïᘅ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var㦼㜸 = new ActionReference();
    varሔO㠊ᐍ = charIDToTypeID("TxLr");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");㦼㜸.putEnumerated(ሔO㠊ᐍ, ꄑҥꄌ, lÒ㨚ć);घĘธïᘅ.putReference(idnull, 㦼㜸);
    varᘂሏ = charIDToTypeID("T   ");
    var욑ҽฏÑ = new ActionDescriptor();
    varꄌùãÈ = charIDToTypeID("Txt ");욑ҽฏÑ.putString(ꄌùãÈ, "圣诞大促销·全sdf场五折起");
    varҾᔅ㢌 = stringIDToTypeID("warp");
    varòñ㘙қS = new ActionDescriptor();
    varҽҨᘀȒpÝҟ = stringIDToTypeID("warpStyle");
    varҽҨᘀȒpÝҟ = stringIDToTypeID("warpStyle");
    varᔆøÔҐฅᐁᘊ = stringIDToTypeID("warpNone");òñ㘙қS.putEnumerated(ҽҨᘀȒpÝҟ, ҽҨᘀȒpÝҟ, ᔆøÔҐฅᐁᘊ);
    varӈӈᘐऍᘌ㨟 = stringIDToTypeID("warpValue");òñ㘙қS.putDouble(ӈӈᘐऍᘌ㨟, 0);
    varҋҬ㜁㠍áÀ쑂ﾍҀ = stringIDToTypeID("warpPerspective");òñ㘙қS.putDouble(ҋҬ㜁㠍áÀ쑂ﾍҀ, 0);
    varꂉ갇ŤҞᐖԅIàd㭱㨵힘 = stringIDToTypeID("warpPerspectiveOther");òñ㘙қS.putDouble(ꂉ갇ŤҞᐖԅIàd㭱㨵힘, 0);
    var隣ŧĘÏÆYrÀù = stringIDToTypeID("warpRotate");
    varӉगԈª = charIDToTypeID("Ornt");
    varȓ욙Ҵ = charIDToTypeID("Hrzn");òñ㘙қS.putEnumerated(隣ŧĘÏÆYrÀù, ӉगԈª, ȓ욙Ҵ);
    varҾᔅ㢌 = stringIDToTypeID("warp");욑ҽฏÑ.putObject(Ҿᔅ㢌, Ҿᔅ㢌, òñ㘙қS);
    var TAæꁲҳǦउᐋᘌ = stringIDToTypeID("textGridding");
    var TAæꁲҳǦउᐋᘌ = stringIDToTypeID("textGridding");
    varทᘎÓ㘌 = charIDToTypeID("None");욑ҽฏÑ.putEnumerated(TAæꁲҳǦउᐋᘌ, TAæꁲҳǦउᐋᘌ, ทᘎÓ㘌);
    varӉगԈª = charIDToTypeID("Ornt");
    varӉगԈª = charIDToTypeID("Ornt");
    varȓ욙Ҵ = charIDToTypeID("Hrzn");욑ҽฏÑ.putEnumerated(ӉगԈª, ӉगԈª, ȓ욙Ҵ);
    varòꄊखघ = charIDToTypeID("AntA");
    varꄕѾ㠆 = charIDToTypeID("Annt");
    varꐴ㢌ý = charIDToTypeID("AnSm");욑ҽฏÑ.putEnumerated(òꄊखघ, ꄕѾ㠆, ꐴ㢌ý);
    varŤǬȖकU = stringIDToTypeID("bounds");
    varǥdҐǥ = new ActionDescriptor();
    varชถÖÔñ = charIDToTypeID("Left");
    var왊홇 = charIDToTypeID("#Pnt");ǥdҐǥ.putUnitDouble(ชถÖÔñ, 왊홇, -347.160889);
    var㜍ᔁᐆ = charIDToTypeID("Top ");
    var왊홇 = charIDToTypeID("#Pnt");ǥdҐǥ.putUnitDouble(㜍ᔁᐆ, 왊홇, -51.333614);
    varกȐԂሎ = charIDToTypeID("Rght");
    var왊홇 = charIDToTypeID("#Pnt");ǥdҐǥ.putUnitDouble(กȐԂሎ, 왊홇, 345.877869);
    varÙ㘘ҸC = charIDToTypeID("Btom");
    var왊홇 = charIDToTypeID("#Pnt");ǥdҐǥ.putUnitDouble(Ù㘘ҸC, 왊홇, 61.016968);
    varŤǬȖकU = stringIDToTypeID("bounds");욑ҽฏÑ.putObject(ŤǬȖकU, ŤǬȖकU, ǥdҐǥ);
    varÃdáØäZᔃᘖᔀᔄg = stringIDToTypeID("boundingBox");
    varԍԉदҡ = new ActionDescriptor();
    varชถÖÔñ = charIDToTypeID("Left");
    var왊홇 = charIDToTypeID("#Pnt");ԍԉदҡ.putUnitDouble(ชถÖÔñ, 왊홇, -344.902954);
    var㜍ᔁᐆ = charIDToTypeID("Top ");
    var왊홇 = charIDToTypeID("#Pnt");ԍԉदҡ.putUnitDouble(㜍ᔁᐆ, 왊홇, -50.027206);
    varกȐԂሎ = charIDToTypeID("Rght");
    var왊홇 = charIDToTypeID("#Pnt");ԍԉदҡ.putUnitDouble(กȐԂሎ, 왊홇, 345.144836);
    varÙ㘘ҸC = charIDToTypeID("Btom");
    var왊홇 = charIDToTypeID("#Pnt");ԍԉदҡ.putUnitDouble(Ù㘘ҸC, 왊홇, 6.229187);
    varÃdáØäZᔃᘖᔀᔄg = stringIDToTypeID("boundingBox");욑ҽฏÑ.putObject(ÃdáØäZᔃᘖᔀᔄg, ÃdáØäZᔃᘖᔀᔄg, ԍԉदҡ);
    var쑹ᘎĐCéý엱 = stringIDToTypeID("textShape");
    var lÇyZAß = new ActionList();
    varȃȗ㘍Ǧ = new ActionDescriptor();
    varᔙᔄᘘฐ = charIDToTypeID("TEXT");
    varᔙᔄᘘฐ = charIDToTypeID("TEXT");
    var왊홇 = charIDToTypeID("Pnt ");ȃȗ㘍Ǧ.putEnumerated(ᔙᔄᘘฐ, ᔙᔄᘘฐ, 왊홇);
    varӉगԈª = charIDToTypeID("Ornt");
    varӉगԈª = charIDToTypeID("Ornt");
    varȓ욙Ҵ = charIDToTypeID("Hrzn");ȃȗ㘍Ǧ.putEnumerated(ӉगԈª, ӉगԈª, ȓ욙Ҵ);
    varᘃFÇ㖠 = charIDToTypeID("Trnf");
    varÖqғҨÊ = new ActionDescriptor();
    varꂀฒ = stringIDToTypeID("xx");ÖqғҨÊ.putDouble(ꂀฒ, 1);
    var㮘Đ = stringIDToTypeID("xy");ÖqғҨÊ.putDouble(㮘Đ, 0);
    var욣ᔍ = stringIDToTypeID("yx");ÖqғҨÊ.putDouble(욣ᔍ, 0);
    var㠋Ҧ = stringIDToTypeID("yy");ÖqғҨÊ.putDouble(㠋Ҧ, 1);
    varᔋꁙ = stringIDToTypeID("tx");ÖqғҨÊ.putDouble(ᔋꁙ, 0);
    varꈳต = stringIDToTypeID("ty");ÖqғҨÊ.putDouble(ꈳต, 0);
    varᘃFÇ㖠 = charIDToTypeID("Trnf");ȃȗ㘍Ǧ.putObject(ᘃFÇ㖠, ᘃFÇ㖠, ÖqғҨÊ);
    varܔȅ㘉㘒ᔎऒ = stringIDToTypeID("rowCount");ȃȗ㘍Ǧ.putInteger(ܔȅ㘉㘒ᔎऒ, 1);
    varÔBꂅ㗹ùvAÌPÊ = stringIDToTypeID("columnCount");ȃȗ㘍Ǧ.putInteger(ÔBꂅ㗹ùvAÌPÊ, 1);
    varĐᘘ㡡ǭ㠌Ӊजᔎ = stringIDToTypeID("rowMajorOrder");ȃȗ㘍Ǧ.putBoolean(Đᘘ㡡ǭ㠌Ӊजᔎ, true);
    var Oथ갇ҠLhXB = stringIDToTypeID("rowGutter");
    var왊홇 = charIDToTypeID("#Pnt");ȃȗ㘍Ǧ.putUnitDouble(Oथ갇ҠLhXB, 왊홇, 0);
    varþÅæñå裡ңţȒO = stringIDToTypeID("columnGutter");
    var왊홇 = charIDToTypeID("#Pnt");ȃȗ㘍Ǧ.putUnitDouble(þÅæñå裡ңţȒO, 왊홇, 0);
    var væFᔉĒ = charIDToTypeID("Spcn");
    var왊홇 = charIDToTypeID("#Pnt");ȃȗ㘍Ǧ.putUnitDouble(væFᔉĒ, 왊홇, 0);
    var y㭷㥱욚㨟요ตܐďซȋऍሔ = stringIDToTypeID("frameBaselineAlignment");
    var y㭷㥱욚㨟요ตܐďซȋऍሔ = stringIDToTypeID("frameBaselineAlignment");
    varąሐᔂÒҊᔍȔȐᘊᘉ = stringIDToTypeID("alignByAscent");ȃȗ㘍Ǧ.putEnumerated(y㭷㥱욚㨟요ตܐďซȋऍሔ, y㭷㥱욚㨟요ตܐďซȋऍሔ, ąሐᔂÒҊᔍȔȐᘊᘉ);
    varꊀEQDqOwá㦾ꉦᾮꁻꉟ = stringIDToTypeID("firstBaselineMinimum");
    var왊홇 = charIDToTypeID("#Pnt");ȃȗ㘍Ǧ.putUnitDouble(ꊀEQDqOwá㦾ꉦᾮꁻꉟ, 왊홇, 0);
    varµᔑȐÔm = stringIDToTypeID("base");
    varďฏÄcҟ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");ďฏÄcҟ.putDouble(ȓ욙Ҵ, 0);
    varҹǬꄏ = charIDToTypeID("Vrtc");ďฏÄcҟ.putDouble(ҹǬꄏ, 0);
    var왊홇 = charIDToTypeID("Pnt ");ȃȗ㘍Ǧ.putObject(µᔑȐÔm, 왊홇, ďฏÄcҟ);
    var쑹ᘎĐCéý엱 = stringIDToTypeID("textShape");
    lÇyZAß.putObject(쑹ᘎĐCéý엱, ȃȗ㘍Ǧ);욑ҽฏÑ.putList(쑹ᘎĐCéý엱, lÇyZAß);
    var엱ꄏĒ = charIDToTypeID("Txtt");
    var GAgùæÜ = new ActionList();
    var bàeæpwù = new ActionDescriptor();
    var H욌Ȏå = charIDToTypeID("From");
    bàeæpwù.putInteger(H욌Ȏå, 0);
    varᘂሏ = charIDToTypeID("T   ");
    bàeæpwù.putInteger(ᘂሏ, 15);
    var왒Ȑçª = charIDToTypeID("TxtS");
    varҟᐇþ㦓 = new ActionDescriptor();
    varĄȖĈýW욣㨢Ὗꑨ엯Ҫ = stringIDToTypeID("styleSheetHasParent");ҟᐇþ㦓.putBoolean(ĄȖĈýW욣㨢Ὗꑨ엯Ҫ, true);
    var㭶үҪҏᘂᘁตሕwUjꊀ = stringIDToTypeID("fontPostScriptName");ҟᐇþ㦓.putString(㭶үҪҏᘂᘁตሕwUjꊀ, "SourceHanSansCN-Bold");
    var CØÁคऋ = charIDToTypeID("FntN");ҟᐇþ㦓.putString(CØÁคऋ, "Source Han Sans CN");
    varดýÝòᐂ = charIDToTypeID("FntS");ҟᐇþ㦓.putString(ดýÝòᐂ, "Bold");
    varҖ㘘Ҹ = charIDToTypeID("Scrp");ҟᐇþ㦓.putInteger(Җ㘘Ҹ, 25);
    varĘ㦾Ҏ = charIDToTypeID("FntT");ҟᐇþ㦓.putInteger(Ę㦾Ҏ, 2);
    varᔄᘌชᐒȊᔒᘎฒØҙ = stringIDToTypeID("fontAvailable");ҟᐇþ㦓.putBoolean(ᔄᘌชᐒȊᔒᘎฒØҙ, true);
    varनHT = charIDToTypeID("Sz  ");
    var왊홇 = charIDToTypeID("#Pnt");ҟᐇþ㦓.putUnitDouble(नHT, 왊홇, 58.333328);
    var pòïdcꈲ㘋ԄyÈdÖÒò = stringIDToTypeID("impliedFontSize");
    var왊홇 = charIDToTypeID("#Pnt");ҟᐇþ㦓.putUnitDouble(pòïdcꈲ㘋ԄyÈdÖÒò, 왊홇, 113.580545);
    varฐėeÂi㯃ᔋᘁȄ = stringIDToTypeID("autoLeading");ҟᐇþ㦓.putBoolean(ฐėeÂi㯃ᔋᘁȄ, false);
    var왅Ǧฃ = charIDToTypeID("Ldng");
    var왊홇 = charIDToTypeID("#Pnt");ҟᐇþ㦓.putUnitDouble(왅Ǧฃ, 왊홇, 69.999992);
    varᾨ㥻料ᘏÓÚᾬꁄ = stringIDToTypeID("impliedLeading");
    var왊홇 = charIDToTypeID("#Pnt");ҟᐇþ㦓.putUnitDouble(ᾨ㥻料ᘏÓÚᾬꁄ, 왊홇, 136.296651);
    var각ҩꄏ = charIDToTypeID("Trck");ҟᐇþ㦓.putInteger(각ҩꄏ, -25);
    varᾯ㡡L = charIDToTypeID("AtKr");
    varᾯ㡡L = charIDToTypeID("AtKr");
    varꁴ㘒ĘÖiꁙ㭮 = stringIDToTypeID("opticalKern");ҟᐇþ㦓.putEnumerated(ᾯ㡡L, ᾯ㡡L, ꁴ㘒ĘÖiꁙ㭮);
    varîªÍҪѾᘏܒ = stringIDToTypeID("fontCaps");
    varîªÍҪѾᘏܒ = stringIDToTypeID("fontCaps");
    varҥfÌå㠌ҫ = stringIDToTypeID("allCaps");ҟᐇþ㦓.putEnumerated(îªÍҪѾᘏܒ, îªÍҪѾᘏܒ, ҥfÌå㠌ҫ);
    varѾŧaHҪǸ = stringIDToTypeID("digitSet");
    varѾŧaHҪǸ = stringIDToTypeID("digitSet");
    varҭआᔑᘄԇฒȕ㜏Ǯ = stringIDToTypeID("defaultDigits");ҟᐇþ㦓.putEnumerated(ѾŧaHҪǸ, ѾŧaHҪǸ, ҭआᔑᘄԇฒȕ㜏Ǯ);
    varꁀ왎㦙ųÃrwÕÓáꁺꉏｿ = stringIDToTypeID("markYDistFromBaseline");
    var왊홇 = charIDToTypeID("#Pnt");ҟᐇþ㦓.putUnitDouble(ꁀ왎㦙ųÃrwÕÓáꁺꉏｿ, 왊홇, 24);
    varԏᐋᔊሖäT㠀थǻ = stringIDToTypeID("textLanguage");
    varԏᐋᔊሖäT㠀थǻ = stringIDToTypeID("textLanguage");
    var iàÚÑÚ㦓㨲Ҳҝꄘฏᐐ = stringIDToTypeID("ukenglishLanguage");ҟᐇþ㦓.putEnumerated(ԏᐋᔊሖäT㠀थǻ, ԏᐋᔊሖäT㠀थǻ, iàÚÑÚ㦓㨲Ҳҝꄘฏᐐ);
    varø㘂íæ = charIDToTypeID("Clr ");
    var rajvîҴ = new ActionDescriptor();
    varÎǩb = charIDToTypeID("Rd  ");
    rajvîҴ.putDouble(Îǩb, 166.000005);
    varǹȅᐐ = charIDToTypeID("Grn ");
    rajvîҴ.putDouble(ǹȅᐐ, 105.000001);
    varċ㭲 = charIDToTypeID("Bl  ");
    rajvîҴ.putDouble(ċ㭲, 70.000003);
    varᔋĐw㜒 = charIDToTypeID("RGBC");ҟᐇþ㦓.putObject(ø㘂íæ, ᔋĐw㜒, rajvîҴ);
    varนᔖሒÍ쑂㘈ܐԎ = stringIDToTypeID("strokeColor");
    varᔇđÒÃýþ = new ActionDescriptor();
    varÎǩb = charIDToTypeID("Rd  ");ᔇđÒÃýþ.putDouble(Îǩb, 255);
    varǹȅᐐ = charIDToTypeID("Grn ");ᔇđÒÃýþ.putDouble(ǹȅᐐ, 255);
    varċ㭲 = charIDToTypeID("Bl  ");ᔇđÒÃýþ.putDouble(ċ㭲, 255);
    varᔋĐw㜒 = charIDToTypeID("RGBC");ҟᐇþ㦓.putObject(นᔖሒÍ쑂㘈ܐԎ, ᔋĐw㜒, ᔇđÒÃýþ);
    var UørÜÓꑠ㥺ꁦŢᔎÊ = stringIDToTypeID("baseParentStyle");
    varÌÉ㦲엮 = new ActionDescriptor();
    var㭶үҪҏᘂᘁตሕwUjꊀ = stringIDToTypeID("fontPostScriptName");ÌÉ㦲엮.putString(㭶үҪҏᘂᘁตሕwUjꊀ, "AdobeHeitiStd-Regular");
    var CØÁคऋ = charIDToTypeID("FntN");ÌÉ㦲엮.putString(CØÁคऋ, "Adobe Heiti Std");
    varดýÝòᐂ = charIDToTypeID("FntS");ÌÉ㦲엮.putString(ดýÝòᐂ, "R");
    varҖ㘘Ҹ = charIDToTypeID("Scrp");ÌÉ㦲엮.putInteger(Җ㘘Ҹ, 25);
    varĘ㦾Ҏ = charIDToTypeID("FntT");ÌÉ㦲엮.putInteger(Ę㦾Ҏ, 2);
    varᔄᘌชᐒȊᔒᘎฒØҙ = stringIDToTypeID("fontAvailable");ÌÉ㦲엮.putBoolean(ᔄᘌชᐒȊᔒᘎฒØҙ, true);
    varनHT = charIDToTypeID("Sz  ");
    var왊홇 = charIDToTypeID("#Pnt");ÌÉ㦲엮.putUnitDouble(नHT, 왊홇, 12);
    var pòïdcꈲ㘋ԄyÈdÖÒò = stringIDToTypeID("impliedFontSize");
    var왊홇 = charIDToTypeID("#Pnt");ÌÉ㦲엮.putUnitDouble(pòïdcꈲ㘋ԄyÈdÖÒò, 왊홇, 23.365143);
    var쑂Ǹᘙ = charIDToTypeID("HrzS");ÌÉ㦲엮.putDouble(쑂Ǹᘙ, 100);
    varܓsðkԃ = charIDToTypeID("VrtS");ÌÉ㦲엮.putDouble(ܓsðkԃ, 100);
    var yìMòª갌갃MÒiétá = stringIDToTypeID("syntheticBold");ÌÉ㦲엮.putBoolean(yìMòª갌갃MÒiétá, false);
    var㜖ҠӀѽҒ㜌㨞㨭 = stringIDToTypeID("syntheticItalic");ÌÉ㦲엮.putBoolean(㜖ҠӀѽҒ㜌㨞㨭, false);
    varฐėeÂi㯃ᔋᘁȄ = stringIDToTypeID("autoLeading");ÌÉ㦲엮.putBoolean(ฐėeÂi㯃ᔋᘁȄ, true);
    var각ҩꄏ = charIDToTypeID("Trck");ÌÉ㦲엮.putInteger(각ҩꄏ, 0);
    varꁝÁꁴ = charIDToTypeID("Bsln");
    var왊홇 = charIDToTypeID("#Pnt");ÌÉ㦲엮.putUnitDouble(ꁝÁꁴ, 왊홇, 0);
    varáÀñÃÒQòÕKµꂄ왍쑶왔㜐 = stringIDToTypeID("impliedBaselineShift");
    var왊홇 = charIDToTypeID("#Pnt");ÌÉ㦲엮.putUnitDouble(áÀñÃÒQòÕKµꂄ왍쑶왔㜐, 왊홇, 0);
    varꑤᔎघïëÁábÊäRñÀjꑟ = stringIDToTypeID("characterRotation");ÌÉ㦲엮.putDouble(ꑤᔎघïëÁábÊäRñÀjꑟ, 0);
    varᾯ㡡L = charIDToTypeID("AtKr");
    varᾯ㡡L = charIDToTypeID("AtKr");
    varȖĒA쑹ꐺӈ㠊 = stringIDToTypeID("metricsKern");ÌÉ㦲엮.putEnumerated(ᾯ㡡L, ᾯ㡡L, ȖĒA쑹ꐺӈ㠊);
    varîªÍҪѾᘏܒ = stringIDToTypeID("fontCaps");
    varîªÍҪѾᘏܒ = stringIDToTypeID("fontCaps");
    varＡᔅgð = charIDToTypeID("Nrml");ÌÉ㦲엮.putEnumerated(îªÍҪѾᘏܒ, îªÍҪѾᘏܒ, Ａᔅgð);
    varѾŧaHҪǸ = stringIDToTypeID("digitSet");
    varѾŧaHҪǸ = stringIDToTypeID("digitSet");
    varҭआᔑᘄԇฒȕ㜏Ǯ = stringIDToTypeID("defaultDigits");ÌÉ㦲엮.putEnumerated(ѾŧaHҪǸ, ѾŧaHҪǸ, ҭआᔑᘄԇฒȕ㜏Ǯ);
    varत㜋ĉSýdUzＺ = stringIDToTypeID("dirOverride");
    varत㜋ĉSýdUzＺ = stringIDToTypeID("dirOverride");
    var㮖㖠ÒrzhµÖLÃXË㯀㦳 = stringIDToTypeID("dirOverrideDefault");ÌÉ㦲엮.putEnumerated(त㜋ĉSýdUzＺ, त㜋ĉSýdUzＺ, 㮖㖠ÒrzhµÖLÃXË㯀㦳);
    varӈҽꄉԄᔉØ = stringIDToTypeID("kashidas");
    varӈҽꄉԄᔉØ = stringIDToTypeID("kashidas");
    var㡝㥭Ҵ㘆㜔ŧᐋă = stringIDToTypeID("kashidaDefault");ÌÉ㦲엮.putEnumerated(ӈҽꄉԄᔉØ, ӈҽꄉԄᔉØ, 㡝㥭Ҵ㘆㜔ŧᐋă);
    varĊUîJúòñ㥚 = stringIDToTypeID("diacVPos");
    varĊUîJúòñ㥚 = stringIDToTypeID("diacVPos");
    varȏԉčᔑß㨛㮓ฉᔅȘᐐ = stringIDToTypeID("diacVPosOpenType");ÌÉ㦲엮.putEnumerated(ĊUîJúòñ㥚, ĊUîJúòñ㥚, ȏԉčᔑß㨛㮓ฉᔅȘᐐ);
    varñꉉ㦵ꐵ왜ǩ = stringIDToTypeID("diacXOffset");
    var왊홇 = charIDToTypeID("#Pnt");ÌÉ㦲엮.putUnitDouble(ñꉉ㦵ꐵ왜ǩ, 왊홇, 0);
    varᐁᘉȒßÌVÃऌሖԏ = stringIDToTypeID("diacYOffset");
    var왊홇 = charIDToTypeID("#Pnt");ÌÉ㦲엮.putUnitDouble(ᐁᘉȒßÌVÃऌሖԏ, 왊홇, 0);
    varꁀ왎㦙ųÃrwÕÓáꁺꉏｿ = stringIDToTypeID("markYDistFromBaseline");
    var왊홇 = charIDToTypeID("#Pnt");ÌÉ㦲엮.putUnitDouble(ꁀ왎㦙ųÃrwÕÓáꁺꉏｿ, 왊홇, 100);
    varµJg엱ꁁÅº = stringIDToTypeID("baseline");
    varµJg엱ꁁÅº = stringIDToTypeID("baseline");
    varＡᔅgð = charIDToTypeID("Nrml");ÌÉ㦲엮.putEnumerated(µJg엱ꁁÅº, µJg엱ꁁÅº, Ａᔅgð);
    var YöcꁗघðóVßþ = stringIDToTypeID("otbaseline");
    var YöcꁗघðóVßþ = stringIDToTypeID("otbaseline");
    varＡᔅgð = charIDToTypeID("Nrml");ÌÉ㦲엮.putEnumerated(YöcꁗघðóVßþ, YöcꁗघðóVßþ, Ａᔅgð);
    varǨꄓDªXꄉӂ㘙त = stringIDToTypeID("strikethrough");
    varǨꄓDªXꄉӂ㘙त = stringIDToTypeID("strikethrough");
    varҿҙîÏyꉘ㦙ҧғ갆 = stringIDToTypeID("strikethroughOff");ÌÉ㦲엮.putEnumerated(ǨꄓDªXꄉӂ㘙त, ǨꄓDªXꄉӂ㘙त, ҿҙîÏyꉘ㦙ҧғ갆);
    varᘍᔅRқ = charIDToTypeID("Undl");
    varᘍᔅRқ = charIDToTypeID("Undl");
    varनúw㘉㘐ǯӇ㜗 = stringIDToTypeID("underlineOff");ÌÉ㦲엮.putEnumerated(ᘍᔅRқ, ᘍᔅRқ, नúw㘉㘐ǯӇ㜗);
    var Aꑡꄖडढ간ฅµLòÀ = stringIDToTypeID("underlineOffset");
    var왊홇 = charIDToTypeID("#Pnt");ÌÉ㦲엮.putUnitDouble(Aꑡꄖडढ간ฅµLòÀ, 왊홇, 0);
    varãyᾪऍĎᘒç = stringIDToTypeID("ligature");ÌÉ㦲엮.putBoolean(ãyᾪऍĎᘒç, true);
    varîÓaꁼ㙦HÓõØÀ = stringIDToTypeID("altligature");ÌÉ㦲엮.putBoolean(îÓaꁼ㙦HÓõØÀ, false);
    var㮒㯀왏ӄꄔꄔҝĖÙûÔÓ = stringIDToTypeID("contextualLigatures");ÌÉ㦲엮.putBoolean(㮒㯀왏ӄꄔꄔҝĖÙûÔÓ, false);
    varሎù㦒왠ꄑᐂกᐍघᘀᘏᐍ = stringIDToTypeID("alternateLigatures");ÌÉ㦲엮.putBoolean(ሎù㦒왠ꄑᐂกᐍघᘀᘏᐍ, false);
    var z㜇㜒㘇ҳc = stringIDToTypeID("oldStyle");ÌÉ㦲엮.putBoolean(z㜇㜒㘇ҳc, false);
    varआᔁ간㘆Ҹҿ = stringIDToTypeID("fractions");ÌÉ㦲엮.putBoolean(आᔁ간㘆Ҹҿ, false);
    varꁞꑙ㜉㘘ð = stringIDToTypeID("ordinals");ÌÉ㦲엮.putBoolean(ꁞꑙ㜉㘘ð, false);
    var v갈ध㜀 = stringIDToTypeID("swash");ÌÉ㦲엮.putBoolean(v갈ध㜀, false);
    var왋ᘍꐻ㨟 = stringIDToTypeID("titling");ÌÉ㦲엮.putBoolean(왋ᘍꐻ㨟, false);
    varêµÖᾪѽӃҡꄈďnÊ = stringIDToTypeID("connectionForms");ÌÉ㦲엮.putBoolean(êµÖᾪѽӃҡꄈďnÊ, false);
    varã왔㮙ꐾꁂүǵᘙȗᐅᘍ = stringIDToTypeID("stylisticAlternates");ÌÉ㦲엮.putBoolean(ã왔㮙ꐾꁂүǵᘙȗᐅᘍ, false);
    var oҲѿҕझúE = stringIDToTypeID("ornaments");ÌÉ㦲엮.putBoolean(oҲѿҕझúE, false);
    var㦔ꐰ쑏㠆ǷᘍङᘓᔇNkÛÆôꐸ = stringIDToTypeID("justificationAlternates");ÌÉ㦲엮.putBoolean(㦔ꐰ쑏㠆ǷᘍङᘓᔇNkÛÆôꐸ, false);
    var oꂅꉡ쑹ᔐZÐÓ = stringIDToTypeID("figureStyle");
    var oꂅꉡ쑹ᔐZÐÓ = stringIDToTypeID("figureStyle");
    varＡᔅgð = charIDToTypeID("Nrml");ÌÉ㦲엮.putEnumerated(oꂅꉡ쑹ᔐZÐÓ, oꂅꉡ쑹ᔐZÐÓ, Ａᔅgð);
    var cqＰꉞꐹ㨞औᘔZñÐÜWs = stringIDToTypeID("proportionalMetrics");ÌÉ㦲엮.putBoolean(cqＰꉞꐹ㨞औᘔZñÐÜWs, false);
    varѸ㘐wl = stringIDToTypeID("kana");ÌÉ㦲엮.putBoolean(Ѹ㘐wl, false);
    varÎWïÕáNҹÎ = stringIDToTypeID("italics");ÌÉ㦲엮.putBoolean(ÎWïÕáNҹÎ, false);
    varܐý㜍ग = stringIDToTypeID("ruby");ÌÉ㦲엮.putBoolean(ܐý㜍ग, false);
    var욘ꁹꄌsÝ㦶㢁ꁥ㭴 = stringIDToTypeID("baselineDirection");
    var욘ꁹꄌsÝ㦶㢁ꁥ㭴 = stringIDToTypeID("baselineDirection");
    varӌदEæA㘈 = stringIDToTypeID("rotated");ÌÉ㦲엮.putEnumerated(욘ꁹꄌsÝ㦶㢁ꁥ㭴, 욘ꁹꄌsÝ㦶㢁ꁥ㭴, ӌदEæA㘈);
    varԏᐋᔊሖäT㠀थǻ = stringIDToTypeID("textLanguage");
    varԏᐋᔊሖäT㠀थǻ = stringIDToTypeID("textLanguage");
    varý욠đऎऋÓéÑKxEZTÇ = stringIDToTypeID("englishLanguage");ÌÉ㦲엮.putEnumerated(ԏᐋᔊሖäT㠀थǻ, ԏᐋᔊሖäT㠀थǻ, ý욠đऎऋÓéÑKxEZTÇ);
    varᾯ쑪ᘙᐊËÏÅóSÄìaÑPÔ = stringIDToTypeID("japaneseAlternate");
    varᾯ쑪ᘙᐊËÏÅóSÄìaÑPÔ = stringIDToTypeID("japaneseAlternate");
    varȂ㥳홉㘔ᐕԌख = stringIDToTypeID("defaultForm");ÌÉ㦲엮.putEnumerated(ᾯ쑪ᘙᐊËÏÅóSÄìaÑPÔ, ᾯ쑪ᘙᐊËÏÅóSÄìaÑPÔ, Ȃ㥳홉㘔ᐕԌख);
    var ußªRꈳąòã = stringIDToTypeID("mojiZume");ÌÉ㦲엮.putDouble(ußªRꈳąòã, 0);
    varõØîWPgOnҝӌऄď = stringIDToTypeID("gridAlignment");
    varõØîWPgOnҝӌऄď = stringIDToTypeID("gridAlignment");
    varÈLôàนᐈ = stringIDToTypeID("roman");ÌÉ㦲엮.putEnumerated(õØîWPgOnҝӌऄď, õØîWPgOnҝӌऄď, ÈLôàนᐈ);
    varÕꁘĊȗሒงԃfºHû = stringIDToTypeID("enableWariChu");ÌÉ㦲엮.putBoolean(ÕꁘĊȗሒงԃfºHû, false);
    varณᔄᐔċȄԇºÅÝêW = stringIDToTypeID("wariChuCount");ÌÉ㦲엮.putInteger(ณᔄᐔċȄԇºÅÝêW, 2);
    varҀ욎홄흵㦵Ӆथ = stringIDToTypeID("wariChuLineGap");ÌÉ㦲엮.putInteger(Ҁ욎홄흵㦵Ӆथ, 0);
    var HíqZíꑁꑩȆᐑÿ = stringIDToTypeID("wariChuScale");ÌÉ㦲엮.putDouble(HíqZíꑁꑩȆᐑÿ, 0.5);
    var rJWÇÏ갂㜖ǶᔍȖ = stringIDToTypeID("wariChuWidow");ÌÉ㦲엮.putInteger(rJWÇÏ갂㜖ǶᔍȖ, 2);
    varᐍĎÎIåÐOþDfëओሔ = stringIDToTypeID("wariChuOrphan");ÌÉ㦲엮.putInteger(ᐍĎÎIåÐOþDfëओሔ, 2);
    varçꂃ㥵ꁰ㕄㭵㜁ҫŢगà = stringIDToTypeID("wariChuJustification");
    varçꂃ㥵ꁰ㕄㭵㜁ҫŢगà = stringIDToTypeID("wariChuJustification");
    varꑩ왅㦲ᐍईญᔇᔏᔋeꁝ = stringIDToTypeID("wariChuAutoJustify");ÌÉ㦲엮.putEnumerated(çꂃ㥵ꁰ㕄㭵㜁ҫŢगà, çꂃ㥵ꁰ㕄㭵㜁ҫŢगà, ꑩ왅㦲ᐍईญᔇᔏᔋeꁝ);
    varĖĔᐅȋӌईĖ = stringIDToTypeID("tcyUpDown");ÌÉ㦲엮.putInteger(ĖĔᐅȋӌईĖ, 0);
    varîҤ㘃चăऄฑԏò = stringIDToTypeID("tcyLeftRight");ÌÉ㦲엮.putInteger(îҤ㘃चăऄฑԏò, 0);
    var nҮ㜂ywrí = stringIDToTypeID("leftAki");ÌÉ㦲엮.putDouble(nҮ㜂ywrí, -1);
    var㜗ढᘒȌS㘋 = stringIDToTypeID("rightAki");ÌÉ㦲엮.putDouble(㜗ढᘒȌS㘋, -1);
    var t왃ᐊēᘅ = stringIDToTypeID("jiDori");ÌÉ㦲엮.putInteger(t왃ᐊēᘅ, 0);
    varċĎᐌᔁGꄔ = stringIDToTypeID("noBreak");ÌÉ㦲엮.putBoolean(ċĎᐌᔁGꄔ, false);
    varø㘂íæ = charIDToTypeID("Clr ");
    var㘉wæIꄏ = new ActionDescriptor();
    varÎǩb = charIDToTypeID("Rd  ");㘉wæIꄏ.putDouble(Îǩb, 0);
    varǹȅᐐ = charIDToTypeID("Grn ");㘉wæIꄏ.putDouble(ǹȅᐐ, 0);
    varċ㭲 = charIDToTypeID("Bl  ");㘉wæIꄏ.putDouble(ċ㭲, 0);
    varᔋĐw㜒 = charIDToTypeID("RGBC");ÌÉ㦲엮.putObject(ø㘂íæ, ᔋĐw㜒, 㘉wæIꄏ);
    varนᔖሒÍ쑂㘈ܐԎ = stringIDToTypeID("strokeColor");
    varꂇ㥬KZ = new ActionDescriptor();
    varÎǩb = charIDToTypeID("Rd  ");ꂇ㥬KZ.putDouble(Îǩb, 0);
    varǹȅᐐ = charIDToTypeID("Grn ");ꂇ㥬KZ.putDouble(ǹȅᐐ, 0);
    varċ㭲 = charIDToTypeID("Bl  ");ꂇ㥬KZ.putDouble(ċ㭲, 0);
    varᔋĐw㜒 = charIDToTypeID("RGBC");ÌÉ㦲엮.putObject(นᔖሒÍ쑂㘈ܐԎ, ᔋĐw㜒, ꂇ㥬KZ);
    varÝÙèý = charIDToTypeID("Fl  ");ÌÉ㦲엮.putBoolean(ÝÙèý, true);
    varºQ㘌Ҭ = charIDToTypeID("Strk");ÌÉ㦲엮.putBoolean(ºQ㘌Ҭ, false);
    varòғ㜌㘁Ҍ갆 = stringIDToTypeID("fillFirst");ÌÉ㦲엮.putBoolean(òғ㜌㘁Ҍ갆, true);
    var idfillOverPrint = stringIDToTypeID("fillOverPrint");ÌÉ㦲엮.putBoolean(idfillOverPrint, false);
    var idstrokeOverPrint = stringIDToTypeID("strokeOverPrint");ÌÉ㦲엮.putBoolean(idstrokeOverPrint, false);
    var㜙ܒÁaàꑠ = stringIDToTypeID("lineCap");
    var㜙ܒÁaàꑠ = stringIDToTypeID("lineCap");
    varԇฉëºYÌ갃 = stringIDToTypeID("buttCap");ÌÉ㦲엮.putEnumerated(㜙ܒÁaàꑠ, 㜙ܒÁaàꑠ, ԇฉëºYÌ갃);
    var idlineJoin = stringIDToTypeID("lineJoin");
    var idlineJoin = stringIDToTypeID("lineJoin");
    var idmiterJoin = stringIDToTypeID("miterJoin");ÌÉ㦲엮.putEnumerated(idlineJoin, idlineJoin, idmiterJoin);
    varþÚý힘ꉍ갂A = stringIDToTypeID("lineWidth");
    var왊홇 = charIDToTypeID("#Pnt");ÌÉ㦲엮.putUnitDouble(þÚý힘ꉍ갂A, 왊홇, 1);
    var EëCZԋᘅᐂᐔeq = stringIDToTypeID("miterLimit");
    var왊홇 = charIDToTypeID("#Pnt");ÌÉ㦲엮.putUnitDouble(EëCZԋᘅᐂᐔeq, 왊홇, 4);
    varíðöõÍÝDｃǬᐐԋܐ = stringIDToTypeID("lineDashoffset");ÌÉ㦲엮.putDouble(íðöõÍÝDｃǬᐐԋܐ, 0);
    var왒Ȑçª = charIDToTypeID("TxtS");ҟᐇþ㦓.putObject(UørÜÓꑠ㥺ꁦŢᔎÊ, 왒Ȑçª, ÌÉ㦲엮);
    var왒Ȑçª = charIDToTypeID("TxtS");
    bàeæpwù.putObject(왒Ȑçª, 왒Ȑçª, ҟᐇþ㦓);
    var엱ꄏĒ = charIDToTypeID("Txtt");
    GAgùæÜ.putObject(엱ꄏĒ, bàeæpwù);욑ҽฏÑ.putList(엱ꄏĒ, GAgùæÜ);
    varûË왜㦔㦲욗ꁥᘓfWMSf = stringIDToTypeID("paragraphStyleRange");
    varगéÅûᐂ = new ActionList();
    var iàðCØNÃ = new ActionDescriptor();
    var H욌Ȏå = charIDToTypeID("From");
    iàðCØNÃ.putInteger(H욌Ȏå, 0);
    varᘂሏ = charIDToTypeID("T   ");
    iàðCØNÃ.putInteger(ᘂሏ, 15);
    varҭइᔅถªýꁿꁨ욋 = stringIDToTypeID("paragraphStyle");
    varđȕǪठ = new ActionDescriptor();
    varĄȖĈýW욣㨢Ὗꑨ엯Ҫ = stringIDToTypeID("styleSheetHasParent");đȕǪठ.putBoolean(ĄȖĈýW욣㨢Ὗꑨ엯Ҫ, true);
    varÜúÈÎ㘏 = charIDToTypeID("Algn");
    varꁱ㨦 = charIDToTypeID("Alg ");
    varधꄑꄑ = charIDToTypeID("Cntr");đȕǪठ.putEnumerated(ÜúÈÎ㘏, ꁱ㨦, धꄑꄑ);
    var Vb욌㮐ᾫ왚㝙㢍욝กPð = stringIDToTypeID("autoLeadingPercentage");đȕǪठ.putDouble(Vb욌㮐ᾫ왚㝙㢍욝กPð, 1.2);
    varǬ㠍㜇ꉐ㦕Ҹ = stringIDToTypeID("leadingType");
    varǬ㠍㜇ꉐ㦕Ҹ = stringIDToTypeID("leadingType");
    varᐒÖlâºiSꁹ㮍Ă = stringIDToTypeID("leadingBelow");đȕǪठ.putEnumerated(Ǭ㠍㜇ꉐ㦕Ҹ, Ǭ㠍㜇ꉐ㦕Ҹ, ᐒÖlâºiSꁹ㮍Ă);
    var㘇ᘈÜ쑤㠍ǭ = stringIDToTypeID("hyphenate");đȕǪठ.putBoolean(㘇ᘈÜ쑤㠍ǭ, true);
    var idjustificationWordMinimum = stringIDToTypeID("justificationWordMinimum");đȕǪठ.putDouble(idjustificationWordMinimum, 0.8);
    var idjustificationWordDesired = stringIDToTypeID("justificationWordDesired");đȕǪठ.putDouble(idjustificationWordDesired, 1);
    var idjustificationWordMaximum = stringIDToTypeID("justificationWordMaximum");đȕǪठ.putDouble(idjustificationWordMaximum, 1.33);
    var idjustificationLetterMinimum = stringIDToTypeID("justificationLetterMinimum");đȕǪठ.putDouble(idjustificationLetterMinimum, 0);
    var idjustificationLetterDesired = stringIDToTypeID("justificationLetterDesired");đȕǪठ.putDouble(idjustificationLetterDesired, 0);
    var idjustificationLetterMaximum = stringIDToTypeID("justificationLetterMaximum");đȕǪठ.putDouble(idjustificationLetterMaximum, 0);
    var idjustificationGlyphMinimum = stringIDToTypeID("justificationGlyphMinimum");đȕǪठ.putDouble(idjustificationGlyphMinimum, 1);
    var idjustificationGlyphDesired = stringIDToTypeID("justificationGlyphDesired");đȕǪठ.putDouble(idjustificationGlyphDesired, 1);
    var idjustificationGlyphMaximum = stringIDToTypeID("justificationGlyphMaximum");đȕǪठ.putDouble(idjustificationGlyphMaximum, 1);
    var g㝙ꈳ㮿㦞งᘓ = stringIDToTypeID("defaultStyle");
    varұ욒㯄 = new ActionDescriptor();
    var㭶үҪҏᘂᘁตሕwUjꊀ = stringIDToTypeID("fontPostScriptName");ұ욒㯄.putString(㭶үҪҏᘂᘁตሕwUjꊀ, "AdobeHeitiStd-Regular");
    var CØÁคऋ = charIDToTypeID("FntN");ұ욒㯄.putString(CØÁคऋ, "Adobe Heiti Std");
    varดýÝòᐂ = charIDToTypeID("FntS");ұ욒㯄.putString(ดýÝòᐂ, "R");
    varҖ㘘Ҹ = charIDToTypeID("Scrp");ұ욒㯄.putInteger(Җ㘘Ҹ, 25);
    varĘ㦾Ҏ = charIDToTypeID("FntT");ұ욒㯄.putInteger(Ę㦾Ҏ, 2);
    varᔄᘌชᐒȊᔒᘎฒØҙ = stringIDToTypeID("fontAvailable");ұ욒㯄.putBoolean(ᔄᘌชᐒȊᔒᘎฒØҙ, true);
    varनHT = charIDToTypeID("Sz  ");
    var왊홇 = charIDToTypeID("#Pnt");ұ욒㯄.putUnitDouble(नHT, 왊홇, 25);
    var쑂Ǹᘙ = charIDToTypeID("HrzS");ұ욒㯄.putDouble(쑂Ǹᘙ, 100);
    varܓsðkԃ = charIDToTypeID("VrtS");ұ욒㯄.putDouble(ܓsðkԃ, 100);
    var yìMòª갌갃MÒiétá = stringIDToTypeID("syntheticBold");ұ욒㯄.putBoolean(yìMòª갌갃MÒiétá, false);
    var㜖ҠӀѽҒ㜌㨞㨭 = stringIDToTypeID("syntheticItalic");ұ욒㯄.putBoolean(㜖ҠӀѽҒ㜌㨞㨭, false);
    varฐėeÂi㯃ᔋᘁȄ = stringIDToTypeID("autoLeading");ұ욒㯄.putBoolean(ฐėeÂi㯃ᔋᘁȄ, true);
    var각ҩꄏ = charIDToTypeID("Trck");ұ욒㯄.putInteger(각ҩꄏ, 0);
    varꁝÁꁴ = charIDToTypeID("Bsln");
    var왊홇 = charIDToTypeID("#Pnt");ұ욒㯄.putUnitDouble(ꁝÁꁴ, 왊홇, 0);
    varꑤᔎघïëÁábÊäRñÀjꑟ = stringIDToTypeID("characterRotation");ұ욒㯄.putDouble(ꑤᔎघïëÁábÊäRñÀjꑟ, 0);
    varᾯ㡡L = charIDToTypeID("AtKr");
    varᾯ㡡L = charIDToTypeID("AtKr");
    var aÚ㮖ऍÿt = stringIDToTypeID("manual");ұ욒㯄.putEnumerated(ᾯ㡡L, ᾯ㡡L, aÚ㮖ऍÿt);
    varîªÍҪѾᘏܒ = stringIDToTypeID("fontCaps");
    varîªÍҪѾᘏܒ = stringIDToTypeID("fontCaps");
    varＡᔅgð = charIDToTypeID("Nrml");ұ욒㯄.putEnumerated(îªÍҪѾᘏܒ, îªÍҪѾᘏܒ, Ａᔅgð);
    varѾŧaHҪǸ = stringIDToTypeID("digitSet");
    varѾŧaHҪǸ = stringIDToTypeID("digitSet");
    varԃᐓሔመᔕfJᔗᔏᔆ = stringIDToTypeID("arabicDigits");ұ욒㯄.putEnumerated(ѾŧaHҪǸ, ѾŧaHҪǸ, ԃᐓሔመᔕfJᔗᔏᔆ);
    varӈҽꄉԄᔉØ = stringIDToTypeID("kashidas");
    varӈҽꄉԄᔉØ = stringIDToTypeID("kashidas");
    var㡝㥭Ҵ㘆㜔ŧᐋă = stringIDToTypeID("kashidaDefault");ұ욒㯄.putEnumerated(ӈҽꄉԄᔉØ, ӈҽꄉԄᔉØ, 㡝㥭Ҵ㘆㜔ŧᐋă);
    varĊUîJúòñ㥚 = stringIDToTypeID("diacVPos");
    varĊUîJúòñ㥚 = stringIDToTypeID("diacVPos");
    varȏԉčᔑß㨛㮓ฉᔅȘᐐ = stringIDToTypeID("diacVPosOpenType");ұ욒㯄.putEnumerated(ĊUîJúòñ㥚, ĊUîJúòñ㥚, ȏԉčᔑß㨛㮓ฉᔅȘᐐ);
    varñꉉ㦵ꐵ왜ǩ = stringIDToTypeID("diacXOffset");
    var왊홇 = charIDToTypeID("#Pnt");ұ욒㯄.putUnitDouble(ñꉉ㦵ꐵ왜ǩ, 왊홇, 0);
    varᐁᘉȒßÌVÃऌሖԏ = stringIDToTypeID("diacYOffset");
    var왊홇 = charIDToTypeID("#Pnt");ұ욒㯄.putUnitDouble(ᐁᘉȒßÌVÃऌሖԏ, 왊홇, 0);
    varꁀ왎㦙ųÃrwÕÓáꁺꉏｿ = stringIDToTypeID("markYDistFromBaseline");
    var왊홇 = charIDToTypeID("#Pnt");ұ욒㯄.putUnitDouble(ꁀ왎㦙ųÃrwÕÓáꁺꉏｿ, 왊홇, 0);
    varµJg엱ꁁÅº = stringIDToTypeID("baseline");
    varµJg엱ꁁÅº = stringIDToTypeID("baseline");
    varＡᔅgð = charIDToTypeID("Nrml");ұ욒㯄.putEnumerated(µJg엱ꁁÅº, µJg엱ꁁÅº, Ａᔅgð);
    varǨꄓDªXꄉӂ㘙त = stringIDToTypeID("strikethrough");
    varǨꄓDªXꄉӂ㘙त = stringIDToTypeID("strikethrough");
    varҿҙîÏyꉘ㦙ҧғ갆 = stringIDToTypeID("strikethroughOff");ұ욒㯄.putEnumerated(ǨꄓDªXꄉӂ㘙त, ǨꄓDªXꄉӂ㘙त, ҿҙîÏyꉘ㦙ҧғ갆);
    varᘍᔅRқ = charIDToTypeID("Undl");
    varᘍᔅRқ = charIDToTypeID("Undl");
    varनúw㘉㘐ǯӇ㜗 = stringIDToTypeID("underlineOff");ұ욒㯄.putEnumerated(ᘍᔅRқ, ᘍᔅRқ, नúw㘉㘐ǯӇ㜗);
    varãyᾪऍĎᘒç = stringIDToTypeID("ligature");ұ욒㯄.putBoolean(ãyᾪऍĎᘒç, true);
    varîÓaꁼ㙦HÓõØÀ = stringIDToTypeID("altligature");ұ욒㯄.putBoolean(îÓaꁼ㙦HÓõØÀ, false);
    var㮒㯀왏ӄꄔꄔҝĖÙûÔÓ = stringIDToTypeID("contextualLigatures");ұ욒㯄.putBoolean(㮒㯀왏ӄꄔꄔҝĖÙûÔÓ, true);
    varሎù㦒왠ꄑᐂกᐍघᘀᘏᐍ = stringIDToTypeID("alternateLigatures");ұ욒㯄.putBoolean(ሎù㦒왠ꄑᐂกᐍघᘀᘏᐍ, false);
    var z㜇㜒㘇ҳc = stringIDToTypeID("oldStyle");ұ욒㯄.putBoolean(z㜇㜒㘇ҳc, false);
    varआᔁ간㘆Ҹҿ = stringIDToTypeID("fractions");ұ욒㯄.putBoolean(आᔁ간㘆Ҹҿ, false);
    varꁞꑙ㜉㘘ð = stringIDToTypeID("ordinals");ұ욒㯄.putBoolean(ꁞꑙ㜉㘘ð, false);
    var v갈ध㜀 = stringIDToTypeID("swash");ұ욒㯄.putBoolean(v갈ध㜀, false);
    var왋ᘍꐻ㨟 = stringIDToTypeID("titling");ұ욒㯄.putBoolean(왋ᘍꐻ㨟, false);
    varêµÖᾪѽӃҡꄈďnÊ = stringIDToTypeID("connectionForms");ұ욒㯄.putBoolean(êµÖᾪѽӃҡꄈďnÊ, false);
    varã왔㮙ꐾꁂүǵᘙȗᐅᘍ = stringIDToTypeID("stylisticAlternates");ұ욒㯄.putBoolean(ã왔㮙ꐾꁂүǵᘙȗᐅᘍ, false);
    var oҲѿҕझúE = stringIDToTypeID("ornaments");ұ욒㯄.putBoolean(oҲѿҕझúE, false);
    var oꂅꉡ쑹ᔐZÐÓ = stringIDToTypeID("figureStyle");
    var oꂅꉡ쑹ᔐZÐÓ = stringIDToTypeID("figureStyle");
    varＡᔅgð = charIDToTypeID("Nrml");ұ욒㯄.putEnumerated(oꂅꉡ쑹ᔐZÐÓ, oꂅꉡ쑹ᔐZÐÓ, Ａᔅgð);
    varԏᐋᔊሖäT㠀थǻ = stringIDToTypeID("textLanguage");
    varԏᐋᔊሖäT㠀थǻ = stringIDToTypeID("textLanguage");
    varý욠đऎऋÓéÑKxEZTÇ = stringIDToTypeID("englishLanguage");ұ욒㯄.putEnumerated(ԏᐋᔊሖäT㠀थǻ, ԏᐋᔊሖäT㠀थǻ, ý욠đऎऋÓéÑKxEZTÇ);
    varø㘂íæ = charIDToTypeID("Clr ");
    var xºëÃwgø = new ActionDescriptor();
    varÎǩb = charIDToTypeID("Rd  ");
    xºëÃwgø.putDouble(Îǩb, 0);
    varǹȅᐐ = charIDToTypeID("Grn ");
    xºëÃwgø.putDouble(ǹȅᐐ, 0);
    varċ㭲 = charIDToTypeID("Bl  ");
    xºëÃwgø.putDouble(ċ㭲, 0);
    varᔋĐw㜒 = charIDToTypeID("RGBC");ұ욒㯄.putObject(ø㘂íæ, ᔋĐw㜒, xºëÃwgø);
    varนᔖሒÍ쑂㘈ܐԎ = stringIDToTypeID("strokeColor");
    varᘓᔙ㘅Ғ = new ActionDescriptor();
    varÎǩb = charIDToTypeID("Rd  ");ᘓᔙ㘅Ғ.putDouble(Îǩb, 0);
    varǹȅᐐ = charIDToTypeID("Grn ");ᘓᔙ㘅Ғ.putDouble(ǹȅᐐ, 0);
    varċ㭲 = charIDToTypeID("Bl  ");ᘓᔙ㘅Ғ.putDouble(ċ㭲, 0);
    varᔋĐw㜒 = charIDToTypeID("RGBC");ұ욒㯄.putObject(นᔖሒÍ쑂㘈ܐԎ, ᔋĐw㜒, ᘓᔙ㘅Ғ);
    var왒Ȑçª = charIDToTypeID("TxtS");đȕǪठ.putObject(g㝙ꈳ㮿㦞งᘓ, 왒Ȑçª, ұ욒㯄);
    varҭइᔅถªýꁿꁨ욋 = stringIDToTypeID("paragraphStyle");
    iàðCØNÃ.putObject(ҭइᔅถªýꁿꁨ욋, ҭइᔅถªýꁿꁨ욋, đȕǪठ);
    varûË왜㦔㦲욗ꁥᘓfWMSf = stringIDToTypeID("paragraphStyleRange");गéÅûᐂ.putObject(ûË왜㦔㦲욗ꁥᘓfWMSf, iàðCØNÃ);욑ҽฏÑ.putList(ûË왜㦔㦲욗ꁥᘓfWMSf, गéÅûᐂ);
    varÛ㦶ชሓᘕÒYÿLÏÅ = stringIDToTypeID("kerningRange");
    varÝöǥǺ = new ActionList();욑ҽฏÑ.putList(Û㦶ชሓᘕÒYÿLÏÅ, ÝöǥǺ);
    varሔO㠊ᐍ = charIDToTypeID("TxLr");घĘธïᘅ.putObject(ᘂሏ, ሔO㠊ᐍ, 욑ҽฏÑ);
    executeAction(ÊU㡜ȑ, घĘธïᘅ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varǼt㘕ꄎ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varᐏkýᔒ = new ActionReference();
    varǭǮȀĘUír = stringIDToTypeID("moveTool");ᐏkýᔒ.putClass(ǭǮȀĘUír);Ǽt㘕ꄎ.putReference(idnull, ᐏkýᔒ);
    varᘀนܓăሕԈऔᐅ = stringIDToTypeID("dontRecord");Ǽt㘕ꄎ.putBoolean(ᘀนܓăሕԈऔᐅ, true);
    varÿÔoòÝÅꉈԄkéO = stringIDToTypeID("forceNotify");Ǽt㘕ꄎ.putBoolean(ÿÔoòÝÅꉈԄkéO, true);
    executeAction(l㦚ꁼ, Ǽt㘕ꄎ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    var QԄखÛòI = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varșңऌ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");șңऌ.putName(ԅÈ㜸, "%off");
    QԄखÛòI.putReference(idnull, șңऌ);
    varŧธĆÔ = charIDToTypeID("MkVs");
    QԄखÛòI.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    varᘂčĄᘘ = new ActionList();ᘂčĄᘘ.putInteger(17);
    QԄखÛòI.putList(㘉झ㘇, ᘂčĄᘘ);
    executeAction(l㦚ꁼ, QԄखÛòI, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varᐌyꉼǩ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ᐌyꉼǩ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ᐌyꉼǩ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varሑሒVงܐ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ሑሒVงܐ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ሑሒVงܐ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ᐌyꉼǩ.putObject(Ǹčฉg, Ǹčฉg, ሑሒVงܐ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ᐌyꉼǩ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ᐌyꉼǩ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ᐌyꉼǩ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varกÍø㜂Ȅ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");กÍø㜂Ȅ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");กÍø㜂Ȅ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varȖê㣱Ǵ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");Ȗê㣱Ǵ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");Ȗê㣱Ǵ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");กÍø㜂Ȅ.putObject(Ǹčฉg, Ǹčฉg, Ȗê㣱Ǵ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");กÍø㜂Ȅ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");กÍø㜂Ȅ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, กÍø㜂Ȅ, DialogModes.NO);
    var神㠌ұ = charIDToTypeID("move");
    varďQԃᘎĕ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varฎîëᘅ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");ฎîëᘅ.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);ďQԃᘎĕ.putReference(idnull, ฎîëᘅ);
    varᘂሏ = charIDToTypeID("T   ");
    var㙇ᐈԅก = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");㙇ᐈԅก.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, -184);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");㙇ᐈԅก.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 296);
    varᔒธxҖ = charIDToTypeID("Ofst");ďQԃᘎĕ.putObject(ᘂሏ, ᔒธxҖ, 㙇ᐈԅก);
    executeAction(神㠌ұ, ďQԃᘎĕ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varᘗȐÖYLw = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varËұӅ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");ËұӅ.putName(ԅÈ㜸, "感恩促销·惠动全城");ᘗȐÖYLw.putReference(idnull, ËұӅ);
    varŧธĆÔ = charIDToTypeID("MkVs");ᘗȐÖYLw.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    varÄ㦎ᔏá = new ActionList();Ä㦎ᔏá.putInteger(24);ᘗȐÖYLw.putList(㘉झ㘇, Ä㦎ᔏá);
    executeAction(l㦚ꁼ, ᘗȐÖYLw, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var㠌ţpmU = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");㠌ţpmU.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");㠌ţpmU.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varëÃÑYöoË = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ëÃÑYöoË.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ëÃÑYöoË.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");㠌ţpmU.putObject(Ǹčฉg, Ǹčฉg, ëÃÑYöoË);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");㠌ţpmU.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");㠌ţpmU.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 㠌ţpmU, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var욏Ҡ㥵 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");욏Ҡ㥵.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");욏Ҡ㥵.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    var U㡋㜊Ȑ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    U㡋㜊Ȑ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    U㡋㜊Ȑ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");욏Ҡ㥵.putObject(Ǹčฉg, Ǹčฉg, U㡋㜊Ȑ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");욏Ҡ㥵.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");욏Ҡ㥵.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 욏Ҡ㥵, DialogModes.NO);
    var神㠌ұ = charIDToTypeID("move");
    var㠌ȑญत = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var㘊ҖN = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");㘊ҖN.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);㠌ȑญत.putReference(idnull, 㘊ҖN);
    varᘂሏ = charIDToTypeID("T   ");
    var왓ꁩट = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");왓ꁩट.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 12);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");왓ꁩट.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, -120);
    varᔒธxҖ = charIDToTypeID("Ofst");㠌ȑญत.putObject(ᘂሏ, ᔒธxҖ, 왓ꁩट);
    executeAction(神㠌ұ, 㠌ȑญत, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varèãRұǺ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varᘎӋȇ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");ᘎӋȇ.putName(ԅÈ㜸, "矩形 3");èãRұǺ.putReference(idnull, ᘎӋȇ);
    varŧธĆÔ = charIDToTypeID("MkVs");èãRұǺ.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    varæçýèíL = new ActionList();æçýèíL.putInteger(22);èãRұǺ.putList(㘉झ㘇, æçýèíL);
    executeAction(l㦚ꁼ, èãRұǺ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varҭeÍaҮ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ҭeÍaҮ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ҭeÍaҮ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varȗᔘखชë = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ȗᔘखชë.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ȗᔘखชë.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ҭeÍaҮ.putObject(Ǹčฉg, Ǹčฉg, ȗᔘखชë);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ҭeÍaҮ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ҭeÍaҮ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ҭeÍaҮ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varÆPmO㠌T = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ÆPmO㠌T.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ÆPmO㠌T.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varéßӇǻë = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");éßӇǻë.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");éßӇǻë.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ÆPmO㠌T.putObject(Ǹčฉg, Ǹčฉg, éßӇǻë);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ÆPmO㠌T.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ÆPmO㠌T.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ÆPmO㠌T, DialogModes.NO);
    var神㠌ұ = charIDToTypeID("move");
    varӌᐔԂǻ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varणMǱ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");णMǱ.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);ӌᐔԂǻ.putReference(idnull, णMǱ);
    varᘂሏ = charIDToTypeID("T   ");
    var l㜀ᘆฃå = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");
    l㜀ᘆฃå.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, -40);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");
    l㜀ᘆฃå.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 56);
    varᔒธxҖ = charIDToTypeID("Ofst");ӌᐔԂǻ.putObject(ᘂሏ, ᔒธxҖ, l㜀ᘆฃå);
    executeAction(神㠌ұ, ӌᐔԂǻ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varÃचșȆÞ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varܐԄ㜈 = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");ܐԄ㜈.putName(ԅÈ㜸, "50");ÃचșȆÞ.putReference(idnull, ܐԄ㜈);
    varŧธĆÔ = charIDToTypeID("MkVs");ÃचșȆÞ.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    var xM㦳ᐊ = new ActionList();
    xM㦳ᐊ.putInteger(15);ÃचșȆÞ.putList(㘉झ㘇, xM㦳ᐊ);
    executeAction(l㦚ꁼ, ÃचșȆÞ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varन갈Qǭ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");न갈Qǭ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");न갈Qǭ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varญ㜘ҫᐓ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ญ㜘ҫᐓ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ญ㜘ҫᐓ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");न갈Qǭ.putObject(Ǹčฉg, Ǹčฉg, ญ㜘ҫᐓ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");न갈Qǭ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");न갈Qǭ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, न갈Qǭ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varढ각㜄å = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ढ각㜄å.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ढ각㜄å.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varइธÔgÏê = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");इธÔgÏê.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");इธÔgÏê.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ढ각㜄å.putObject(Ǹčฉg, Ǹčฉg, इธÔgÏê);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ढ각㜄å.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ढ각㜄å.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ढ각㜄å, DialogModes.NO);
    var神㠌ұ = charIDToTypeID("move");
    varĂåดआᔏ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varᔔVèᔒ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");ᔔVèᔒ.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);Ăåดआᔏ.putReference(idnull, ᔔVèᔒ);
    varᘂሏ = charIDToTypeID("T   ");
    var㠍㠉ชᔘ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");㠍㠉ชᔘ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 16);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");㠍㠉ชᔘ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, -76);
    varᔒธxҖ = charIDToTypeID("Ofst");Ăåดआᔏ.putObject(ᘂሏ, ᔒธxҖ, 㠍㠉ชᔘ);
    executeAction(神㠌ұ, Ăåดआᔏ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varҤѽӈÇ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varธӆᐓ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");ธӆᐓ.putName(ԅÈ㜸, "矢量智能对象");ҤѽӈÇ.putReference(idnull, ธӆᐓ);
    varŧธĆÔ = charIDToTypeID("MkVs");ҤѽӈÇ.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    var쑳㜌ȉ = new ActionList();쑳㜌ȉ.putInteger(10);ҤѽӈÇ.putList(㘉झ㘇, 쑳㜌ȉ);
    executeAction(l㦚ꁼ, ҤѽӈÇ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var㘓욋㖫 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");㘓욋㖫.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");㘓욋㖫.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    var G署ओõG = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    G署ओõG.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    G署ओõG.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");㘓욋㖫.putObject(Ǹčฉg, Ǹčฉg, G署ओõG);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");㘓욋㖫.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");㘓욋㖫.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 㘓욋㖫, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var qÒxùöfÐ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");
    qÒxùöfÐ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");
    qÒxùöfÐ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varᐂÙऒऒᐉ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ᐂÙऒऒᐉ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ᐂÙऒऒᐉ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");
    qÒxùöfÐ.putObject(Ǹčฉg, Ǹčฉg, ᐂÙऒऒᐉ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");
    qÒxùöfÐ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");
    qÒxùöfÐ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, qÒxùöfÐ, DialogModes.NO);
    var神㠌ұ = charIDToTypeID("move");
    varꑘꄊὗ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varꉡ왟 = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");ꉡ왟.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);ꑘꄊὗ.putReference(idnull, ꉡ왟);
    varᘂሏ = charIDToTypeID("T   ");
    varऄขNytx = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ऄขNytx.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 108);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ऄขNytx.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, -56);
    varᔒธxҖ = charIDToTypeID("Ofst");ꑘꄊὗ.putObject(ᘂሏ, ᔒธxҖ, ऄขNytx);
    executeAction(神㠌ұ, ꑘꄊὗ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varýÉ쑵ᘃt = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var간ÚҘ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");간ÚҘ.putName(ԅÈ㜸, "颜色填充 2");ýÉ쑵ᘃt.putReference(idnull, 간ÚҘ);
    varŧธĆÔ = charIDToTypeID("MkVs");ýÉ쑵ᘃt.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    varꁣӂܔ = new ActionList();ꁣӂܔ.putInteger(3);ýÉ쑵ᘃt.putList(㘉झ㘇, ꁣӂܔ);
    executeAction(l㦚ꁼ, ýÉ쑵ᘃt, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varÆᘉᘄÕùÙ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ÆᘉᘄÕùÙ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ÆᘉᘄÕùÙ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varēKꁝछ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ēKꁝछ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ēKꁝछ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ÆᘉᘄÕùÙ.putObject(Ǹčฉg, Ǹčฉg, ēKꁝछ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ÆᘉᘄÕùÙ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ÆᘉᘄÕùÙ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ÆᘉᘄÕùÙ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varᔌᘑ㠆Ҡ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ᔌᘑ㠆Ҡ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ᔌᘑ㠆Ҡ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varङȇꉤȉ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ङȇꉤȉ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ङȇꉤȉ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ᔌᘑ㠆Ҡ.putObject(Ǹčฉg, Ǹčฉg, ङȇꉤȉ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ᔌᘑ㠆Ҡ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ᔌᘑ㠆Ҡ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ᔌᘑ㠆Ҡ, DialogModes.NO);
}

// 选择所有图层
function myy_dsd2882w(ᘋĊฉᐓ) {
    // 选中所有图层事件
    var idSelect = stringIDToTypeID("selectAllLayers");
    var desc1 = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var ar1 = new ActionReference();
    var idLayer1 = charIDToTypeID("Lyr "); // layer
    var idOrder1 = charIDToTypeID("Ordn"); // ordinal 顺序
    var iaTargt = charIDToTypeID("Trgt");  // target Enum 目标枚举
    ar1.putEnumerated(  idLayer1,   idOrder1, iaTargt);
    desc1.putReference(idnull, ar1);
    executeAction(idSelect,  desc1, DialogModes.NO);
}

function myy_d882w() {
    var ar1 = new ActionReference();
    ar1.putEnumerated(charIDToTypeID("Lyr "), charIDToTypeID("Ordn"), charIDToTypeID("Trgt"));
    var keys = executeActionGet( ar1).getObjectValue(stringIDToTypeID("textKey"));
    if (keys.hasKey(stringIDToTypeID("transform"))) {
        var transformkey =  keys.getObjectValue(stringIDToTypeID("transform"));
        var val =  transformkey.getUnitDoubleValue(stringIDToTypeID("yy"));
        return  val;
    }
    return 1;
}

function myy_wanMei(z, Z, h) {
    var神㠌ұ = charIDToTypeID("move");
    var힘힙㜊 = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varҳpòj = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");ҳpòj.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);힘힙㜊.putReference(idnull, ҳpòj);
    varᘂሏ = charIDToTypeID("T   ");
    varÖéठҾC = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÖéठҾC.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, -56);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÖéठҾC.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 48);
    varᔒธxҖ = charIDToTypeID("Ofst");힘힙㜊.putObject(ᘂሏ, ᔒธxҖ, ÖéठҾC);
    executeAction(神㠌ұ, 힘힙㜊, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varòÎjFÐük = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var㜅ᘀԃ = new ActionReference();
    var㘁zïFÿ = charIDToTypeID("Dcmn");㜅ᘀԃ.putOffset(㘁zïFÿ, -1);òÎjFÐük.putReference(idnull, 㜅ᘀԃ);
    varêcꐱԋ = charIDToTypeID("DocI");òÎjFÐük.putInteger(êcꐱԋ, 474);
    executeAction(l㦚ꁼ, òÎjFÐük, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varčȃง㗧 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");čȃง㗧.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");čȃง㗧.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varþEOõxÉf = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");þEOõxÉf.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");þEOõxÉf.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");čȃง㗧.putObject(Ǹčฉg, Ǹčฉg, þEOõxÉf);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");čȃง㗧.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");čȃง㗧.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, čȃง㗧, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varᐕÎiAæउ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ᐕÎiAæउ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ᐕÎiAæउ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varҡꄉᘋᘁ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ҡꄉᘋᘁ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ҡꄉᘋᘁ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ᐕÎiAæउ.putObject(Ǹčฉg, Ǹčฉg, ҡꄉᘋᘁ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ᐕÎiAæउ.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᐗऑĄगCÕ = stringIDToTypeID("commit");ᐕÎiAæउ.putEnumerated(ᘁėܐꄑܔ, ᘁėܐꄑܔ, ᐗऑĄगCÕ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ᐕÎiAæउ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ᐕÎiAæउ, DialogModes.NO);
    varᘃFÇ㖠 = charIDToTypeID("Trnf");
    var쑵갆ᘁæ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var rUJZç = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");
    rUJZç.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);쑵갆ᘁæ.putReference(idnull, rUJZç);
    var㠉ᐉ욈 = charIDToTypeID("FTcs");
    varꄓฉꑞ = charIDToTypeID("QCSt");
    varｿᐁûÒ = charIDToTypeID("Qcsa");쑵갆ᘁæ.putEnumerated(㠉ᐉ욈, ꄓฉꑞ, ｿᐁûÒ);
    varᔒธxҖ = charIDToTypeID("Ofst");
    varꁾ㘕ᘓÀ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ꁾ㘕ᘓÀ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 0);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ꁾ㘕ᘓÀ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 0);
    varᔒธxҖ = charIDToTypeID("Ofst");쑵갆ᘁæ.putObject(ᔒธxҖ, ᔒธxҖ, ꁾ㘕ᘓÀ);
    varÝéfćข = charIDToTypeID("Wdth");
    var㥳㝙 = charIDToTypeID("#Prc");쑵갆ᘁæ.putUnitDouble(Ýéfćข, 㥳㝙, 147.560976);
    varþ왎ęý = charIDToTypeID("Hght");
    var㥳㝙 = charIDToTypeID("#Prc");쑵갆ᘁæ.putUnitDouble(þ왎ęý, 㥳㝙, 147.560976);
    varđ㥯㠀 = charIDToTypeID("Intr");
    varᔕāओณ = charIDToTypeID("Intp");
    var WҙébK = charIDToTypeID("Bcbc");쑵갆ᘁæ.putEnumerated(đ㥯㠀, ᔕāओณ, WҙébK);
    executeAction(ᘃFÇ㖠, 쑵갆ᘁæ, DialogModes.NO);
}

function myy_DuquShuJu(z, Z, h) {
    var神㠌ұ = charIDToTypeID("move");
    var힘힙㜊 = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varҳpòj = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");ҳpòj.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);힘힙㜊.putReference(idnull, ҳpòj);
    varᘂሏ = charIDToTypeID("T   ");
    varÖéठҾC = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÖéठҾC.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, -56);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÖéठҾC.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 48);
    varᔒธxҖ = charIDToTypeID("Ofst");힘힙㜊.putObject(ᘂሏ, ᔒธxҖ, ÖéठҾC);
    executeAction(神㠌ұ, 힘힙㜊, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varòÎjFÐük = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var㜅ᘀԃ = new ActionReference();
    var㘁zïFÿ = charIDToTypeID("Dcmn");㜅ᘀԃ.putOffset(㘁zïFÿ, -1);òÎjFÐük.putReference(idnull, 㜅ᘀԃ);
    varêcꐱԋ = charIDToTypeID("DocI");òÎjFÐük.putInteger(êcꐱԋ, 474);
    executeAction(l㦚ꁼ, òÎjFÐük, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varčȃง㗧 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");čȃง㗧.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");čȃง㗧.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varþEOõxÉf = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");þEOõxÉf.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");þEOõxÉf.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");čȃง㗧.putObject(Ǹčฉg, Ǹčฉg, þEOõxÉf);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");čȃง㗧.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");čȃง㗧.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, čȃง㗧, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varᐕÎiAæउ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ᐕÎiAæउ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ᐕÎiAæउ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varҡꄉᘋᘁ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ҡꄉᘋᘁ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ҡꄉᘋᘁ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ᐕÎiAæउ.putObject(Ǹčฉg, Ǹčฉg, ҡꄉᘋᘁ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ᐕÎiAæउ.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᐗऑĄगCÕ = stringIDToTypeID("commit");ᐕÎiAæउ.putEnumerated(ᘁėܐꄑܔ, ᘁėܐꄑܔ, ᐗऑĄगCÕ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ᐕÎiAæउ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ᐕÎiAæउ, DialogModes.NO);
    varᘃFÇ㖠 = charIDToTypeID("Trnf");
    var쑵갆ᘁæ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var rUJZç = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");
    rUJZç.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);쑵갆ᘁæ.putReference(idnull, rUJZç);
    var㠉ᐉ욈 = charIDToTypeID("FTcs");
    varꄓฉꑞ = charIDToTypeID("QCSt");
    varｿᐁûÒ = charIDToTypeID("Qcsa");쑵갆ᘁæ.putEnumerated(㠉ᐉ욈, ꄓฉꑞ, ｿᐁûÒ);
    varᔒธxҖ = charIDToTypeID("Ofst");
    varꁾ㘕ᘓÀ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ꁾ㘕ᘓÀ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 0);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ꁾ㘕ᘓÀ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 0);
    varᔒธxҖ = charIDToTypeID("Ofst");쑵갆ᘁæ.putObject(ᔒธxҖ, ᔒธxҖ, ꁾ㘕ᘓÀ);
    varÝéfćข = charIDToTypeID("Wdth");
    var㥳㝙 = charIDToTypeID("#Prc");쑵갆ᘁæ.putUnitDouble(Ýéfćข, 㥳㝙, 147.560976);
    varþ왎ęý = charIDToTypeID("Hght");
    var㥳㝙 = charIDToTypeID("#Prc");쑵갆ᘁæ.putUnitDouble(þ왎ęý, 㥳㝙, 147.560976);
    varđ㥯㠀 = charIDToTypeID("Intr");
    varᔕāओณ = charIDToTypeID("Intp");
    var WҙébK = charIDToTypeID("Bcbc");쑵갆ᘁæ.putEnumerated(đ㥯㠀, ᔕāओณ, WҙébK);
    executeAction(ᘃFÇ㖠, 쑵갆ᘁæ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varÏ㜍Ďሔu = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var JøÁꄓ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    JøÁꄓ.putName(ԅÈ㜸, "椭圆 1");Ï㜍Ďሔu.putReference(idnull, JøÁꄓ);
    varŧธĆÔ = charIDToTypeID("MkVs");Ï㜍Ďሔu.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    varËf㨭ᘇ = new ActionList();Ëf㨭ᘇ.putInteger(2);Ï㜍Ďሔu.putList(㘉झ㘇, Ëf㨭ᘇ);
    executeAction(l㦚ꁼ, Ï㜍Ďሔu, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var㦏ǭᐄÚ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");㦏ǭᐄÚ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");㦏ǭᐄÚ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    var zÄHùNRÂ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    zÄHùNRÂ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    zÄHùNRÂ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");㦏ǭᐄÚ.putObject(Ǹčฉg, Ǹčฉg, zÄHùNRÂ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");㦏ǭᐄÚ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");㦏ǭᐄÚ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 㦏ǭᐄÚ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var㜇㠇Ėܔ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");㜇㠇Ėܔ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");㜇㠇Ėܔ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    var wvòGødh = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    wvòGødh.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    wvòGødh.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");㜇㠇Ėܔ.putObject(Ǹčฉg, Ǹčฉg, wvòGødh);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");㜇㠇Ėܔ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");㜇㠇Ėܔ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 㜇㠇Ėܔ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varÇťӂұ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");Çťӂұ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");Çťӂұ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varËãȁईAÎ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ËãȁईAÎ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ËãȁईAÎ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");Çťӂұ.putObject(Ǹčฉg, Ǹčฉg, ËãȁईAÎ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");Çťӂұ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");Çťӂұ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, Çťӂұ, DialogModes.NO);
    var神㠌ұ = charIDToTypeID("move");
    varงᔐoÓÈW = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varꄇᐖԏ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");ꄇᐖԏ.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);งᔐoÓÈW.putReference(idnull, ꄇᐖԏ);
    varᘂሏ = charIDToTypeID("T   ");
    varĉȍÃØwÚ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ĉȍÃØwÚ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, -109);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ĉȍÃØwÚ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, -14);
    varᔒธxҖ = charIDToTypeID("Ofst");งᔐoÓÈW.putObject(ᘂሏ, ᔒธxҖ, ĉȍÃØwÚ);
    executeAction(神㠌ұ, งᔐoÓÈW, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varÑÚaNÎÙä = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ÑÚaNÎÙä.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ÑÚaNÎÙä.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varԉԈöxꄖ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ԉԈöxꄖ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ԉԈöxꄖ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ÑÚaNÎÙä.putObject(Ǹčฉg, Ǹčฉg, ԉԈöxꄖ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ÑÚaNÎÙä.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ÑÚaNÎÙä.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ÑÚaNÎÙä, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varǫ㘇G갆 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ǫ㘇G갆.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ǫ㘇G갆.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varÙP홄ȋÙ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ÙP홄ȋÙ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ÙP홄ȋÙ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ǫ㘇G갆.putObject(Ǹčฉg, Ǹčฉg, ÙP홄ȋÙ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ǫ㘇G갆.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ǫ㘇G갆.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ǫ㘇G갆, DialogModes.NO);
    varÃÛÖâҭ = charIDToTypeID("copy");
    var TìᐗȓòÜ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var왝ꑘ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");왝ꑘ.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);
    TìᐗȓòÜ.putReference(idnull, 왝ꑘ);
    varᘂሏ = charIDToTypeID("T   ");
    varǫ㘒Ëꄖ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ǫ㘒Ëꄖ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 109);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ǫ㘒Ëꄖ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, -82);
    varᔒธxҖ = charIDToTypeID("Ofst");
    TìᐗȓòÜ.putObject(ᘂሏ, ᔒธxҖ, ǫ㘒Ëꄖ);
    executeAction(ÃÛÖâҭ, TìᐗȓòÜ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var裡㖥hç = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");裡㖥hç.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");裡㖥hç.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    var料裏ǹ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");料裏ǹ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");料裏ǹ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");裡㖥hç.putObject(Ǹčฉg, Ǹčฉg, 料裏ǹ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");裡㖥hç.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");裡㖥hç.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 裡㖥hç, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varęęҎӇ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ęęҎӇ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ęęҎӇ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    var pêԉȀÁû = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    pêԉȀÁû.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    pêԉȀÁû.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ęęҎӇ.putObject(Ǹčฉg, Ǹčฉg, pêԉȀÁû);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ęęҎӇ.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ęęҎӇ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ęęҎӇ, DialogModes.NO);
    varÃÛÖâҭ = charIDToTypeID("copy");
    varҏሔėÌy = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varóꁧᘑ = new ActionReference();
    varԅÈ㜸 = charIDToTypeID("Lyr ");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");óꁧᘑ.putEnumerated(ԅÈ㜸, ꄑҥꄌ, lÒ㨚ć);ҏሔėÌy.putReference(idnull, óꁧᘑ);
    varᘂሏ = charIDToTypeID("T   ");
    var bC㥭ธÉ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");
    bC㥭ธÉ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 47);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");
    bC㥭ธÉ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 139);
    varᔒธxҖ = charIDToTypeID("Ofst");ҏሔėÌy.putObject(ᘂሏ, ᔒธxҖ, bC㥭ธÉ);
    executeAction(ÃÛÖâҭ, ҏሔėÌy, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varԄÆꁛ㜆 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ԄÆꁛ㜆.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ԄÆꁛ㜆.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    var yKꉿฏe = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    yKꉿฏe.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    yKꉿฏe.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ԄÆꁛ㜆.putObject(Ǹčฉg, Ǹčฉg, yKꉿฏe);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ԄÆꁛ㜆.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᐗऑĄगCÕ = stringIDToTypeID("commit");ԄÆꁛ㜆.putEnumerated(ᘁėܐꄑܔ, ᘁėܐꄑܔ, ᐗऑĄगCÕ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ԄÆꁛ㜆.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ԄÆꁛ㜆, DialogModes.NO);
    varᘃFÇ㖠 = charIDToTypeID("Trnf");
    var엯㮖îµ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var㜺㖤 = new ActionReference();
    var㘇㘊ꄓ = charIDToTypeID("Path");
    varꄑҥꄌ = charIDToTypeID("Ordn");
    var lÒ㨚ć = charIDToTypeID("Trgt");㜺㖤.putEnumerated(㘇㘊ꄓ, ꄑҥꄌ, lÒ㨚ć);엯㮖îµ.putReference(idnull, 㜺㖤);
    var㠉ᐉ욈 = charIDToTypeID("FTcs");
    varꄓฉꑞ = charIDToTypeID("QCSt");
    varｿᐁûÒ = charIDToTypeID("Qcsa");엯㮖îµ.putEnumerated(㠉ᐉ욈, ꄓฉꑞ, ｿᐁûÒ);
    varᔒธxҖ = charIDToTypeID("Ofst");
    varÂõQVâÝÁ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÂõQVâÝÁ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 0.5);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÂõQVâÝÁ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 0.5);
    varᔒธxҖ = charIDToTypeID("Ofst");엯㮖îµ.putObject(ᔒธxҖ, ᔒธxҖ, ÂõQVâÝÁ);
    varÝéfćข = charIDToTypeID("Wdth");
    var㥳㝙 = charIDToTypeID("#Prc");엯㮖îµ.putUnitDouble(Ýéfćข, 㥳㝙, 53.04878);
    varþ왎ęý = charIDToTypeID("Hght");
    var㥳㝙 = charIDToTypeID("#Prc");엯㮖îµ.putUnitDouble(þ왎ęý, 㥳㝙, 53.04878);
    executeAction(ᘃFÇ㖠, 엯㮖îµ, DialogModes.NO);
}