function myy_DuquShuJu(z, Z, h) {
    var	idMove = charIDToTypeID("move");
    var	desc1 = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var	ref1 = new ActionReference();
    var	idLayer = charIDToTypeID("Lyr ");
    var	idOrd1 = charIDToTypeID("Ordn");
    var 	idTargetEnmu = charIDToTypeID("Trgt");
    ref1.putEnumerated(	idLayer, 	idOrd1, 	idTargetEnmu);
    desc1.putReference(idnull, 	ref1);
    var	idTo = charIDToTypeID("T   "); // to
    varÖéठҾC = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÖéठҾC.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, -56);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÖéठҾC.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 48);
    varᔒธxҖ = charIDToTypeID("Ofst");	desc1.putObject(	idTo, ᔒธxҖ, ÖéठҾC);
    executeAction(	idMove, 	desc1, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varòÎjFÐük = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var㜅ᘀԃ = new ActionReference();
    var㘁zïFÿ = charIDToTypeID("Dcmn");㜅ᘀԃ.putOffset(㘁zïFÿ, -1);òÎjFÐük.putReference(idnull, 㜅ᘀԃ);
    varêcꐱԋ = charIDToTypeID("DocI");òÎjFÐük.putInteger(êcꐱԋ, 474);
    executeAction(l㦚ꁼ, òÎjFÐük, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varčȃง㗧 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");čȃง㗧.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");čȃง㗧.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varþEOõxÉf = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");þEOõxÉf.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");þEOõxÉf.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");čȃง㗧.putObject(Ǹčฉg, Ǹčฉg, þEOõxÉf);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");čȃง㗧.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");čȃง㗧.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, čȃง㗧, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varᐕÎiAæउ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ᐕÎiAæउ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ᐕÎiAæउ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varҡꄉᘋᘁ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ҡꄉᘋᘁ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ҡꄉᘋᘁ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ᐕÎiAæउ.putObject(Ǹčฉg, Ǹčฉg, ҡꄉᘋᘁ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ᐕÎiAæउ.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᐗऑĄगCÕ = stringIDToTypeID("commit");ᐕÎiAæउ.putEnumerated(ᘁėܐꄑܔ, ᘁėܐꄑܔ, ᐗऑĄगCÕ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ᐕÎiAæउ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ᐕÎiAæउ, DialogModes.NO);
    varᘃFÇ㖠 = charIDToTypeID("Trnf");
    var쑵갆ᘁæ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var rUJZç = new ActionReference();
    var	idLayer = charIDToTypeID("Lyr ");
    var	idOrd1 = charIDToTypeID("Ordn");
    var 	idTargetEnmu = charIDToTypeID("Trgt");
    rUJZç.putEnumerated(	idLayer, 	idOrd1, 	idTargetEnmu);쑵갆ᘁæ.putReference(idnull, rUJZç);
    var㠉ᐉ욈 = charIDToTypeID("FTcs");
    varꄓฉꑞ = charIDToTypeID("QCSt");
    varｿᐁûÒ = charIDToTypeID("Qcsa");쑵갆ᘁæ.putEnumerated(㠉ᐉ욈, ꄓฉꑞ, ｿᐁûÒ);
    varᔒธxҖ = charIDToTypeID("Ofst");
    varꁾ㘕ᘓÀ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ꁾ㘕ᘓÀ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 0);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ꁾ㘕ᘓÀ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 0);
    varᔒธxҖ = charIDToTypeID("Ofst");쑵갆ᘁæ.putObject(ᔒธxҖ, ᔒธxҖ, ꁾ㘕ᘓÀ);
    varÝéfćข = charIDToTypeID("Wdth");
    var㥳㝙 = charIDToTypeID("#Prc");쑵갆ᘁæ.putUnitDouble(Ýéfćข, 㥳㝙, 147.560976);
    varþ왎ęý = charIDToTypeID("Hght");
    var㥳㝙 = charIDToTypeID("#Prc");쑵갆ᘁæ.putUnitDouble(þ왎ęý, 㥳㝙, 147.560976);
    varđ㥯㠀 = charIDToTypeID("Intr");
    varᔕāओณ = charIDToTypeID("Intp");
    var WҙébK = charIDToTypeID("Bcbc");쑵갆ᘁæ.putEnumerated(đ㥯㠀, ᔕāओณ, WҙébK);
    executeAction(ᘃFÇ㖠, 쑵갆ᘁæ, DialogModes.NO);
    var l㦚ꁼ = charIDToTypeID("slct");
    varÏ㜍Ďሔu = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var JøÁꄓ = new ActionReference();
    var	idLayer = charIDToTypeID("Lyr ");
    JøÁꄓ.putName(	idLayer, "椭圆 1");Ï㜍Ďሔu.putReference(idnull, JøÁꄓ);
    varŧธĆÔ = charIDToTypeID("MkVs");Ï㜍Ďሔu.putBoolean(ŧธĆÔ, false);
    var㘉झ㘇 = charIDToTypeID("LyrI");
    varËf㨭ᘇ = new ActionList();Ëf㨭ᘇ.putInteger(2);Ï㜍Ďሔu.putList(㘉झ㘇, Ëf㨭ᘇ);
    executeAction(l㦚ꁼ, Ï㜍Ďሔu, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var㦏ǭᐄÚ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");㦏ǭᐄÚ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");㦏ǭᐄÚ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    var zÄHùNRÂ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    zÄHùNRÂ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    zÄHùNRÂ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");㦏ǭᐄÚ.putObject(Ǹčฉg, Ǹčฉg, zÄHùNRÂ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");㦏ǭᐄÚ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");㦏ǭᐄÚ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 㦏ǭᐄÚ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var㜇㠇Ėܔ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");㜇㠇Ėܔ.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");㜇㠇Ėܔ.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    var wvòGødh = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    wvòGødh.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    wvòGødh.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");㜇㠇Ėܔ.putObject(Ǹčฉg, Ǹčฉg, wvòGødh);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");㜇㠇Ėܔ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");㜇㠇Ėܔ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 㜇㠇Ėܔ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varÇťӂұ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");Çťӂұ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");Çťӂұ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varËãȁईAÎ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ËãȁईAÎ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ËãȁईAÎ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");Çťӂұ.putObject(Ǹčฉg, Ǹčฉg, ËãȁईAÎ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");Çťӂұ.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");Çťӂұ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, Çťӂұ, DialogModes.NO);
    var	idMove = charIDToTypeID("move");
    varงᔐoÓÈW = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varꄇᐖԏ = new ActionReference();
    var	idLayer = charIDToTypeID("Lyr ");
    var	idOrd1 = charIDToTypeID("Ordn");
    var 	idTargetEnmu = charIDToTypeID("Trgt");ꄇᐖԏ.putEnumerated(	idLayer, 	idOrd1, 	idTargetEnmu);งᔐoÓÈW.putReference(idnull, ꄇᐖԏ);
    var	idTo = charIDToTypeID("T   ");
    varĉȍÃØwÚ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ĉȍÃØwÚ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, -109);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ĉȍÃØwÚ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, -14);
    varᔒธxҖ = charIDToTypeID("Ofst");งᔐoÓÈW.putObject(	idTo, ᔒธxҖ, ĉȍÃØwÚ);
    executeAction(	idMove, งᔐoÓÈW, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varÑÚaNÎÙä = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ÑÚaNÎÙä.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ÑÚaNÎÙä.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    varԉԈöxꄖ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ԉԈöxꄖ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ԉԈöxꄖ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ÑÚaNÎÙä.putObject(Ǹčฉg, Ǹčฉg, ԉԈöxꄖ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ÑÚaNÎÙä.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ÑÚaNÎÙä.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ÑÚaNÎÙä, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varǫ㘇G갆 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ǫ㘇G갆.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ǫ㘇G갆.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    varÙP홄ȋÙ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");ÙP홄ȋÙ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");ÙP홄ȋÙ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ǫ㘇G갆.putObject(Ǹčฉg, Ǹčฉg, ÙP홄ȋÙ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");ǫ㘇G갆.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ǫ㘇G갆.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ǫ㘇G갆, DialogModes.NO);
    varÃÛÖâҭ = charIDToTypeID("copy");
    var TìᐗȓòÜ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var왝ꑘ = new ActionReference();
    var	idLayer = charIDToTypeID("Lyr ");
    var	idOrd1 = charIDToTypeID("Ordn");
    var 	idTargetEnmu = charIDToTypeID("Trgt");왝ꑘ.putEnumerated(	idLayer, 	idOrd1, 	idTargetEnmu);
    TìᐗȓòÜ.putReference(idnull, 왝ꑘ);
    var	idTo = charIDToTypeID("T   ");
    varǫ㘒Ëꄖ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ǫ㘒Ëꄖ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 109);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ǫ㘒Ëꄖ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, -82);
    varᔒธxҖ = charIDToTypeID("Ofst");
    TìᐗȓòÜ.putObject(	idTo, ᔒธxҖ, ǫ㘒Ëꄖ);
    executeAction(ÃÛÖâҭ, TìᐗȓòÜ, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    var裡㖥hç = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");裡㖥hç.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");裡㖥hç.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    var料裏ǹ = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");料裏ǹ.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");料裏ǹ.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");裡㖥hç.putObject(Ǹčฉg, Ǹčฉg, 料裏ǹ);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varҀǳҳÎ = stringIDToTypeID("mouse");裡㖥hç.putEnumerated(Ìþbjg, Ìþbjg, ҀǳҳÎ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");裡㖥hç.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, 裡㖥hç, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varęęҎӇ = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ęęҎӇ.putInteger(왆惡, 1);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԏăԇꁪ = stringIDToTypeID("enter");ęęҎӇ.putEnumerated(㭵Șow, 㭵Șow, ԏăԇꁪ);
    varǸčฉg = charIDToTypeID("Tool");
    var pêԉȀÁû = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    pêԉȀÁû.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    pêԉȀÁû.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ęęҎӇ.putObject(Ǹčฉg, Ǹčฉg, pêԉȀÁû);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ęęҎӇ.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ęęҎӇ.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ęęҎӇ, DialogModes.NO);
    varÃÛÖâҭ = charIDToTypeID("copy");
    varҏሔėÌy = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    varóꁧᘑ = new ActionReference();
    var	idLayer = charIDToTypeID("Lyr ");
    var	idOrd1 = charIDToTypeID("Ordn");
    var 	idTargetEnmu = charIDToTypeID("Trgt");óꁧᘑ.putEnumerated(	idLayer, 	idOrd1, 	idTargetEnmu);ҏሔėÌy.putReference(idnull, óꁧᘑ);
    var	idTo = charIDToTypeID("T   ");
    var bC㥭ธÉ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");
    bC㥭ธÉ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 47);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");
    bC㥭ธÉ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 139);
    varᔒธxҖ = charIDToTypeID("Ofst");ҏሔėÌy.putObject(	idTo, ᔒธxҖ, bC㥭ธÉ);
    executeAction(ÃÛÖâҭ, ҏሔėÌy, DialogModes.NO);
    var㜸㘍चᐁVëgÜZ욋㦐㥳㨜 = stringIDToTypeID("toolModalStateChanged");
    varԄÆꁛ㜆 = new ActionDescriptor();
    var왆惡 = charIDToTypeID("Lvl ");ԄÆꁛ㜆.putInteger(왆惡, 0);
    var㭵Șow = charIDToTypeID("Stte");
    var㭵Șow = charIDToTypeID("Stte");
    varԌË갊Ԋ = stringIDToTypeID("exit");ԄÆꁛ㜆.putEnumerated(㭵Șow, 㭵Șow, ԌË갊Ԋ);
    varǸčฉg = charIDToTypeID("Tool");
    var yKꉿฏe = new ActionDescriptor();
    var wûҴðÂ = charIDToTypeID("Idnt");
    yKꉿฏe.putString(wûҴðÂ, "arwT");
    var욖왛 = charIDToTypeID("Ttl ");
    yKꉿฏe.putString(욖왛, "移动工具");
    varǸčฉg = charIDToTypeID("Tool");ԄÆꁛ㜆.putObject(Ǹčฉg, Ǹčฉg, yKꉿฏe);
    varÌþbjg = charIDToTypeID("Knd ");
    varÌþbjg = charIDToTypeID("Knd ");
    varǸčฉg = charIDToTypeID("Tool");ԄÆꁛ㜆.putEnumerated(Ìþbjg, Ìþbjg, Ǹčฉg);
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᘁėܐꄑܔ = stringIDToTypeID("reason");
    varᐗऑĄगCÕ = stringIDToTypeID("commit");ԄÆꁛ㜆.putEnumerated(ᘁėܐꄑܔ, ᘁėܐꄑܔ, ᐗऑĄगCÕ);
    var홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ = stringIDToTypeID("kcanDispatchWhileModal");ԄÆꁛ㜆.putBoolean(홍㭳㘒Ǻ㜀ᘅԏꐾｾꐼꀼ, true);
    executeAction(㜸㘍चᐁVëgÜZ욋㦐㥳㨜, ԄÆꁛ㜆, DialogModes.NO);
    varᘃFÇ㖠 = charIDToTypeID("Trnf");
    var엯㮖îµ = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var㜺㖤 = new ActionReference();
    var㘇㘊ꄓ = charIDToTypeID("Path");
    var	idOrd1 = charIDToTypeID("Ordn");
    var 	idTargetEnmu = charIDToTypeID("Trgt");㜺㖤.putEnumerated(㘇㘊ꄓ, 	idOrd1, 	idTargetEnmu);엯㮖îµ.putReference(idnull, 㜺㖤);
    var㠉ᐉ욈 = charIDToTypeID("FTcs");
    varꄓฉꑞ = charIDToTypeID("QCSt");
    varｿᐁûÒ = charIDToTypeID("Qcsa");엯㮖îµ.putEnumerated(㠉ᐉ욈, ꄓฉꑞ, ｿᐁûÒ);
    varᔒธxҖ = charIDToTypeID("Ofst");
    varÂõQVâÝÁ = new ActionDescriptor();
    varȓ욙Ҵ = charIDToTypeID("Hrzn");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÂõQVâÝÁ.putUnitDouble(ȓ욙Ҵ, ᔋᐈҰ, 0.5);
    varҹǬꄏ = charIDToTypeID("Vrtc");
    varᔋᐈҰ = charIDToTypeID("#Pxl");ÂõQVâÝÁ.putUnitDouble(ҹǬꄏ, ᔋᐈҰ, 0.5);
    varᔒธxҖ = charIDToTypeID("Ofst");엯㮖îµ.putObject(ᔒธxҖ, ᔒธxҖ, ÂõQVâÝÁ);
    varÝéfćข = charIDToTypeID("Wdth");
    var㥳㝙 = charIDToTypeID("#Prc");엯㮖îµ.putUnitDouble(Ýéfćข, 㥳㝙, 53.04878);
    varþ왎ęý = charIDToTypeID("Hght");
    var㥳㝙 = charIDToTypeID("#Prc");엯㮖îµ.putUnitDouble(þ왎ęý, 㥳㝙, 53.04878);
    executeAction(ᘃFÇ㖠, 엯㮖îµ, DialogModes.NO);
}